### ISSUE TITLE
Issues compiling AITemplate for Stable Diffusion v2

### ISSUE THREAD

**Issue by Suhail** [facebookincubator/AITemplate#103]
Might this have to do with the output shape? `AIT output_0 shape: [1, 64, 768]`

Also, v2 uses OpenCLIP so maybe that's related as well.

```
AIT output_0 shape: [1, 64, 768]
2022-11-24 21:23:10,971 INFO <aitemplate.backend.target> Loading profile cache from: /home/ubuntu/.aitemplate/cuda.db
2022-11-24 21:23:10,971 INFO <aitemplate.backend.profiler_cache> table_name='cuda_gemm_1' exists in the db
2022-11-24 21:23:10,971 INFO <aitemplate.backend.profiler_cache> Trying to make a new gemm table with self._gemm_cache_version=1
Traceback (most recent call last):
  File "compile.py", line 373, in <module>
    compile_diffusers()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "compile.py", line 349, in compile_diffusers
    compile_clip(
  File "compile.py", line 252, in compile_clip
    compile_model(Y, target, "./tmp", "CLIPTextModel", constants=params_ait)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/aitemplate/compiler/compiler.py", line 164, in compile_model
    compiler.transform.bind_constants(graph, constants)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/aitemplate/compiler/transform/bind_constants.py", line 53, in bind_constants
    tensor._bind_data(_TorchConstantTensorData(constants[name]))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/aitemplate/compiler/base.py", line 520, in _bind_data
    raise ValueError(
ValueError: ConstantTensor's maximum size is not equal to len(data)! Got len(data)=101187584, but expected at least 75890688 bytes. Check that the ConstantTensor's size and dtype are correct.
rm: cannot remove 'profiler': No such file or directory
INFO:aitemplate.testing.detect_target:Set target to CUDA
```

I tried just changing the huggingface model name and upgrading diffusers to main (`pip install --upgrade git+https://github.com/huggingface/diffusers.git transformers accelerate scipy`):

```diff
diff --git a/examples/05_stable_diffusion/compile.py b/examples/05_stable_diffusion/compile.py
index 9c87f41..2713fbb 100644
--- a/examples/05_stable_diffusion/compile.py
+++ b/examples/05_stable_diffusion/compile.py
@@ -336,7 +336,7 @@ def compile_diffusers(
         access_token = token

     pipe = StableDiffusionPipeline.from_pretrained(
-        "runwayml/stable-diffusion-v1-5",
+        "stabilityai/stable-diffusion-2-base",
         revision="fp16",
         torch_dtype=torch.float16,
         use_auth_token=access_token,
diff --git a/examples/05_stable_diffusion/demo.py b/examples/05_stable_diffusion/demo.py
index 51859e8..b011b5d 100644
--- a/examples/05_stable_diffusion/demo.py
+++ b/examples/05_stable_diffusion/demo.py
@@ -29,7 +29,7 @@ from pipeline_stable_diffusion_ait import StableDiffusionAITPipeline
 )
 def run(token, width, height, prompt, benchmark):
     pipe = StableDiffusionAITPipeline.from_pretrained(
-        "runwayml/stable-diffusion-v1-5",
+        "stabilityai/stable-diffusion-2-base",
         revision="fp16",
         torch_dtype=torch.float16,
         use_auth_token=token,
```

Info:
- Ubuntu 20.04.5 LTS
- GPU: NVIDIA A100
- diffusers: 0.9.0.dev0

**Comment by hlky** [comment]
Yes, changes are required for ViT-H

I have CLIP compiled on `stabilityai/stable-diffusion-2`. Will try unet and vae now

Pull request soon:tm:

```
AIT output_0 shape: [1, 64, 1024]
2022-11-24 23:17:45,967 INFO <aitemplate.backend.target> Loading profile cache from: /root/.aitemplate/cuda.db
2022-11-24 23:17:45,971 INFO <aitemplate.backend.profiler_cache> table_name='cuda_gemm_1' does not exist in the db, version mismatch!
2022-11-24 23:17:45,971 INFO <aitemplate.backend.profiler_cache> temporarily keep old cache versions
2022-11-24 23:17:45,971 INFO <aitemplate.backend.profiler_cache> Trying to make a new gemm table with self._gemm_cache_version=1
2022-11-24 23:17:50,553 INFO <aitemplate.compiler.compiler> optimized graph elapsed time: 0:00:00.648505
```

```
2022-11-24 23:21:00,952 INFO <aitemplate.compiler.compiler> compiled the final .so file elapsed time: 0:01:20.018516
[23:21:01] model-generated.h:280: Init AITemplate Runtime.
```

```
/AITemplate# ls -lah tmp/CLIPTextModel/test.so
-rwxr-xr-x 1 root root 389M Nov 24 23:21 tmp/CLIPTextModel/test.so
```

**Comment by hlky** [comment]
Minimal changes required for UNet. Compiling now

**Comment by terrychenism** [comment]
fix by https://github.com/facebookincubator/AITemplate/pull/105
