### ISSUE TITLE
accelerate stable diffusion inpainting pipeline

### ISSUE THREAD

**Issue by songjin321** [facebookincubator/AITemplate#123]
**Hello, I want use AITemplate to speed stable diffusion inpainting pipeline, but I meet error when i compile unet module due to the input tensor size is [64,64,9], can you tell me how to solve this problem?**

Traceback (most recent call last):
  File "/home/star/projects/stable_diffusion_eas/AITemplate/examples/05_stable_diffusion/compile.py", line 385, in <module>
    compile_diffusers()
  File "/home/star/miniconda3/envs/diffusers/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/star/miniconda3/envs/diffusers/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/star/miniconda3/envs/diffusers/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/star/miniconda3/envs/diffusers/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/star/projects/stable_diffusion_eas/AITemplate/examples/05_stable_diffusion/compile.py", line 366, in compile_diffusers
    compile_unet(
  File "/home/star/projects/stable_diffusion_eas/AITemplate/examples/05_stable_diffusion/compile.py", line 216, in compile_unet
    compile_model(Y, target, "./tmp_inpaint", "UNet2DConditionModel", constants=params_ait)
  File "/home/star/miniconda3/envs/diffusers/lib/python3.9/site-packages/aitemplate/compiler/compiler.py", line 200, in compile_model
    compiler.transform.profile(
  File "/home/star/miniconda3/envs/diffusers/lib/python3.9/site-packages/aitemplate/compiler/transform/profile.py", line 103, in profile
    f.profile(
  File "/home/star/miniconda3/envs/diffusers/lib/python3.9/site-packages/aitemplate/compiler/ops/conv/conv2d.py", line 458, in profile
    self._profile_static(workdir, devices)
  File "/home/star/miniconda3/envs/diffusers/lib/python3.9/site-packages/aitemplate/compiler/ops/conv/conv2d.py", line 498, in _profile_static
    best_algo, workspace = self._profile_single_workload(
  File "/home/star/miniconda3/envs/diffusers/lib/python3.9/site-packages/aitemplate/compiler/ops/conv/conv2d.py", line 408, in _profile_single_workload
    if not func(cfg, self._attrs, x_shape):
  File "/home/star/miniconda3/envs/diffusers/lib/python3.9/site-packages/aitemplate/backend/cuda/conv2d/conv2d_bias.py", line 86, in conv2d_function_filter
    return common.function_filter(cfg, func_attrs, x_shape)
  File "/home/star/miniconda3/envs/diffusers/lib/python3.9/site-packages/aitemplate/backend/cuda/conv2d/common.py", line 246, in function_filter
    ab_alignment = cal_align_ab(x_shape)
  File "/home/star/miniconda3/envs/diffusers/lib/python3.9/site-packages/aitemplate/backend/cuda/conv2d/common.py", line 226, in cal_align_ab
    raise RuntimeError(f"a/b is not aligned {x_shape=}")
RuntimeError: a/b is not aligned x_shape=[2, 64, 64, 9]

**Comment by chavinlo** [comment]
Did you ever got it to work?
