### ISSUE TITLE
AIT 0.2 crash while compiling model

### ISSUE THREAD

**Issue by carlushuang** [facebookincubator/AITemplate#154]
After install AIT 0.2 and run the SD example, seems crash while compiling the model. The log is like below:
One possible reason is when running `python3 setup.py` while creating the ait package, the `aitemplate/3rdparty/cutlass/include/cute` folder is not copied to current `AITemplate/python/build/lib/aitemplate/3rdparty/cutlass`, resulting in final missing of this folder after install to `/opt/conda/lib/python3.8/site-packages/aitemplate/`

```
2023-01-30 11:46:22,607 INFO <aitemplate.backend.builder> compiling 3 profiler sources
2023-01-30 11:46:22,607 INFO <aitemplate.backend.builder> linking 3 profiler executables
2023-01-30 11:46:22,873 INFO <aitemplate.backend.builder> make stdout:

make: Entering directory '/dockerx/repo/AITemplate/examples/05_stable_diffusion/tmp/profiler'
rm -f gemm_rcr_bias_permute/gemm_rcr_bias_permute_30d331b46ca1799ff6ead39ab17266cdc17ffea8_1 gemm_rcr_bias_add/gemm_rcr_bias_add_9e46850d5286ecc7e078b5b7f76afbcac62967b4_1 gemm_rcr_bias_gelu/gemm_rcr_bias_gelu_9e46850d5286ecc7e078b5b7f76afbcac62967b4_1
make: Leaving directory '/dockerx/repo/AITemplate/examples/05_stable_diffusion/tmp/profiler'
make: Entering directory '/dockerx/repo/AITemplate/examples/05_stable_diffusion/tmp/profiler'
nvcc -DCUTLASS_ENABLE_TENSOR_CORE_MMA=1 -DCUTLASS_USE_TANH_FOR_SIGMOID=1 -w -gencode=arch=compute_80,code=[sm_80,compute_80] -Xcompiler=-fPIC -Xcompiler=-Wconversion -Xcompiler=-fno-strict-aliasing -Xcompiler -fvisibility=hidden -O3 -std=c++17 --expt-relaxed-constexpr --use_fast_math -I/opt/conda/lib/python3.8/site-packages/aitemplate/3rdparty/cutlass/include -I/opt/conda/lib/python3.8/site-packages/aitemplate/3rdparty/cutlass/tools/util/include -I/opt/conda/lib/python3.8/site-packages/aitemplate/3rdparty/cutlass/examples/35_gemm_softmax -I/opt/conda/lib/python3.8/site-packages/aitemplate/3rdparty/cutlass/examples/41_fused_multi_head_attention -I/opt/conda/lib/python3.8/site-packages/aitemplate/3rdparty/cutlass/examples/45_dual_gemm -I/opt/conda/lib/python3.8/site-packages/aitemplate/3rdparty/cutlass/../../backend/cuda/attention/src/./ -I/opt/conda/lib/python3.8/site-packages/aitemplate/3rdparty/cutlass/../../backend/cuda/attention/src/fmha -DNDEBUG -o gemm_rcr_bias_permute/gemm_rcr_bias_permute_30d331b46ca1799ff6ead39ab17266cdc17ffea8_1 gemm_rcr_bias_permute/gemm_rcr_bias_permute_30d331b46ca1799ff6ead39ab17266cdc17ffea8_1.cu
make: Leaving directory '/dockerx/repo/AITemplate/examples/05_stable_diffusion/tmp/profiler'
make: Entering directory '/dockerx/repo/AITemplate/examples/05_stable_diffusion/tmp/profiler'
nvcc -DCUTLASS_ENABLE_TENSOR_CORE_MMA=1 -DCUTLASS_USE_TANH_FOR_SIGMOID=1 -w -gencode=arch=compute_80,code=[sm_80,compute_80] -Xcompiler=-fPIC -Xcompiler=-Wconversion -Xcompiler=-fno-strict-aliasing -Xcompiler -fvisibility=hidden -O3 -std=c++17 --expt-relaxed-constexpr --use_fast_math -I/opt/conda/lib/python3.8/site-packages/aitemplate/3rdparty/cutlass/include -I/opt/conda/lib/python3.8/site-packages/aitemplate/3rdparty/cutlass/tools/util/include -I/opt/conda/lib/python3.8/site-packages/aitemplate/3rdparty/cutlass/examples/35_gemm_softmax -I/opt/conda/lib/python3.8/site-packages/aitemplate/3rdparty/cutlass/examples/41_fused_multi_head_attention -I/opt/conda/lib/python3.8/site-packages/aitemplate/3rdparty/cutlass/examples/45_dual_gemm -I/opt/conda/lib/python3.8/site-packages/aitemplate/3rdparty/cutlass/../../backend/cuda/attention/src/./ -I/opt/conda/lib/python3.8/site-packages/aitemplate/3rdparty/cutlass/../../backend/cuda/attention/src/fmha -DNDEBUG -o gemm_rcr_bias_gelu/gemm_rcr_bias_gelu_9e46850d5286ecc7e078b5b7f76afbcac62967b4_1 gemm_rcr_bias_gelu/gemm_rcr_bias_gelu_9e46850d5286ecc7e078b5b7f76afbcac62967b4_1.cu
make: Leaving directory '/dockerx/repo/AITemplate/examples/05_stable_diffusion/tmp/profiler'
make: Entering directory '/dockerx/repo/AITemplate/examples/05_stable_diffusion/tmp/profiler'
nvcc -DCUTLASS_ENABLE_TENSOR_CORE_MMA=1 -DCUTLASS_USE_TANH_FOR_SIGMOID=1 -w -gencode=arch=compute_80,code=[sm_80,compute_80] -Xcompiler=-fPIC -Xcompiler=-Wconversion -Xcompiler=-fno-strict-aliasing -Xcompiler -fvisibility=hidden -O3 -std=c++17 --expt-relaxed-constexpr --use_fast_math -I/opt/conda/lib/python3.8/site-packages/aitemplate/3rdparty/cutlass/include -I/opt/conda/lib/python3.8/site-packages/aitemplate/3rdparty/cutlass/tools/util/include -I/opt/conda/lib/python3.8/site-packages/aitemplate/3rdparty/cutlass/examples/35_gemm_softmax -I/opt/conda/lib/python3.8/site-packages/aitemplate/3rdparty/cutlass/examples/41_fused_multi_head_attention -I/opt/conda/lib/python3.8/site-packages/aitemplate/3rdparty/cutlass/examples/45_dual_gemm -I/opt/conda/lib/python3.8/site-packages/aitemplate/3rdparty/cutlass/../../backend/cuda/attention/src/./ -I/opt/conda/lib/python3.8/site-packages/aitemplate/3rdparty/cutlass/../../backend/cuda/attention/src/fmha -DNDEBUG -o gemm_rcr_bias_add/gemm_rcr_bias_add_9e46850d5286ecc7e078b5b7f76afbcac62967b4_1 gemm_rcr_bias_add/gemm_rcr_bias_add_9e46850d5286ecc7e078b5b7f76afbcac62967b4_1.cu
make: Leaving directory '/dockerx/repo/AITemplate/examples/05_stable_diffusion/tmp/profiler'

2023-01-30 11:46:22,873 INFO <aitemplate.backend.builder> make stderr:

In file included from /opt/conda/lib/python3.8/site-packages/aitemplate/3rdparty/cutlass/include/cutlass/gemm/gemm.h:38,
                 from /opt/conda/lib/python3.8/site-packages/aitemplate/3rdparty/cutlass/include/cutlass/gemm/device/gemm_universal.h:42,
                 from gemm_rcr_bias_permute/gemm_rcr_bias_permute_30d331b46ca1799ff6ead39ab17266cdc17ffea8_1.cu:13:
/opt/conda/lib/python3.8/site-packages/aitemplate/3rdparty/cutlass/include/cutlass/layout/matrix.h:42:10: fatal error: cute/layout.hpp: No such file or directory
   42 | #include "cute/layout.hpp"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:6: gemm_rcr_bias_permute/gemm_rcr_bias_permute_30d331b46ca1799ff6ead39ab17266cdc17ffea8_1] Error 1
make: *** Waiting for unfinished jobs....
In file included from /opt/conda/lib/python3.8/site-packages/aitemplate/3rdparty/cutlass/include/cutlass/gemm/gemm.h:38,
                 from /opt/conda/lib/python3.8/site-packages/aitemplate/3rdparty/cutlass/include/cutlass/gemm/device/gemm_universal.h:42,
                 from gemm_rcr_bias_gelu/gemm_rcr_bias_gelu_9e46850d5286ecc7e078b5b7f76afbcac62967b4_1.cu:13:
/opt/conda/lib/python3.8/site-packages/aitemplate/3rdparty/cutlass/include/cutlass/layout/matrix.h:42:10: fatal error: cute/layout.hpp: No such file or directory
   42 | #include "cute/layout.hpp"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:12: gemm_rcr_bias_gelu/gemm_rcr_bias_gelu_9e46850d5286ecc7e078b5b7f76afbcac62967b4_1] Error 1
In file included from /opt/conda/lib/python3.8/site-packages/aitemplate/3rdparty/cutlass/include/cutlass/gemm/gemm.h:38,
                 from /opt/conda/lib/python3.8/site-packages/aitemplate/3rdparty/cutlass/include/cutlass/gemm/device/gemm_universal_with_broadcast.h:45,
                 from gemm_rcr_bias_add/gemm_rcr_bias_add_9e46850d5286ecc7e078b5b7f76afbcac62967b4_1.cu:14:
/opt/conda/lib/python3.8/site-packages/aitemplate/3rdparty/cutlass/include/cutlass/layout/matrix.h:42:10: fatal error: cute/layout.hpp: No such file or directory
   42 | #include "cute/layout.hpp"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:9: gemm_rcr_bias_add/gemm_rcr_bias_add_9e46850d5286ecc7e078b5b7f76afbcac62967b4_1] Error 1

Traceback (most recent call last):
  File "compile.py", line 379, in <module>
    compile_diffusers()
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "compile.py", line 353, in compile_diffusers
    compile_clip(
  File "compile.py", line 256, in compile_clip
    compile_model(Y, target, "./tmp", "CLIPTextModel", constants=params_ait)
  File "/opt/conda/lib/python3.8/site-packages/aitemplate/compiler/compiler.py", line 200, in compile_model
    compiler.transform.profile(
  File "/opt/conda/lib/python3.8/site-packages/aitemplate/compiler/transform/profile.py", line 89, in profile
    compile_engine.make_profilers(generated_profilers, profiler_dir)
  File "/opt/conda/lib/python3.8/site-packages/aitemplate/backend/builder.py", line 727, in make_profilers
    _run_make_cmds(cmds, self._timeout, build_dir)
  File "/opt/conda/lib/python3.8/site-packages/aitemplate/backend/builder.py", line 155, in _run_make_cmds
    raise RuntimeError("Build has failed.")
RuntimeError: Build has failed.

```

**Comment by carlushuang** [comment]
https://github.com/facebookincubator/AITemplate/blob/745e17238db099f964754376ace8e5e5c47c691d/python/setup.py#L76-L83

root cause is when copy cutlass files, only copy with ".h"/".cuh" extension. cutlass new release introduced lots of headers endswith **".hpp"** (like that in cutllass/include/cute/). I guess it's due to not fully synced with develop code?

**Comment by chenyang78** [comment]
@carlushuang Thank you for reporting the issue! I think we have a pending PR to fix it:

https://github.com/facebookincubator/AITemplate/pull/152

**Comment by ipiszy** [comment]
Hi @carlushuang , sorry for the issue, https://github.com/facebookincubator/AITemplate/pull/152 has been merged, could you please try again?

**Comment by carlushuang** [comment]
@ipiszy @chenyang78 thanks, after #152, no crash any more

**Comment by carlushuang** [comment]
fixed
