### ISSUE TITLE
ModuleNotFoundError: No module named 'fx2ait.passes'

### ISSUE THREAD

**Issue by bes-dev** [facebookincubator/AITemplate#211]
Env:
GPU: Nvidia A100 PCIE
CPU: AMD EPYC 7742
OS: Ubuntu 22.04
GCC: 11.3.0
CUDA: 11.8
cuDNN: 8.7.0

Install AITemaple:
```bash
cd python
python setup.py bdist_wheel
pip install dist/*.whl --force-reinstall
```

Install fx2ait:
```bash
cd fx2ait
python setup.py install
```

Run example:
```bash
cd AITemplate/fx2ait/fx2ait/example/02_vision_model/
python3 test_vision_model.py
```

Output:
```
INFO:aitemplate.testing.detect_target:Set target to CUDA
Traceback (most recent call last):
  File "/root/work/AITemplate/fx2ait/fx2ait/example/02_vision_model/test_vision_model.py", line 19, in <module>
    from fx2ait.example.benchmark_utils import benchmark_function, verify_accuracy
  File "/usr/local/lib/python3.10/dist-packages/fx2ait-0.2.dev1-py3.10-linux-x86_64.egg/fx2ait/__init__.py", line 17, in <module>
  File "/usr/local/lib/python3.10/dist-packages/fx2ait-0.2.dev1-py3.10-linux-x86_64.egg/fx2ait/converters/__init__.py", line 16, in <module>
  File "/usr/local/lib/python3.10/dist-packages/fx2ait-0.2.dev1-py3.10-linux-x86_64.egg/fx2ait/converters/aten2ait_converters.py", line 65, in <module>
ModuleNotFoundError: No module named 'fx2ait.passes'
```

**Comment by panshaohua** [comment]
https://github.com/facebookincubator/AITemplate/issues/162
