### ISSUE TITLE
Failing to complete tuning for 03-bert example KeyError: 'exec_path'

### ISSUE THREAD

**Issue by causten** [facebookincubator/AITemplate#23]
AITemplate/examples/03_bert# python3 benchmark_ait.py
Using ROCM on MI250

```
2022-10-05 22:15:06,791 INFO <aitemplate.backend.builder> Using 256 CPU for building
2022-10-05 22:15:06,791 INFO <aitemplate.compiler.ops.gemm_universal.gemm_common> Profile: gemm_rcr_bias_permute_m2n3_1: M == 64 && N == 2304 && K == 768
2022-10-05 22:15:06,791 INFO <aitemplate.compiler.ops.gemm_universal.gemm_common> Profile: bmm_softmax_bmm_permute_7: B == 12 && M == 64 && N == 64 && K == 64 && O == 64
2022-10-05 22:15:06,791 INFO <aitemplate.compiler.ops.gemm_universal.gemm_common> Profile: gemm_rcr_bias_add_10: M == 64 && N == 768 && K == 768
2022-10-05 22:15:06,791 INFO <aitemplate.compiler.ops.layernorm.layernorm> Profile: layernorm_13: M == 64 && N == 768
2022-10-05 22:15:06,791 INFO <aitemplate.compiler.ops.layernorm.layernorm> Load profiling result from cache.
2022-10-05 22:15:06,791 INFO <aitemplate.compiler.ops.gemm_universal.gemm_common> Profile: gemm_rcr_bias_fast_gelu_14: M == 64 && N == 3072 && K == 768
2022-10-05 22:15:06,791 INFO <aitemplate.compiler.ops.gemm_universal.gemm_common> Profile: gemm_rcr_bias_add_15: M == 64 && N == 768 && K == 3072
Traceback (most recent call last):
  File "benchmark_ait.py", line 298, in <module>
    compile_and_benchmark()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "benchmark_ait.py", line 284, in compile_and_benchmark
    mod = compile_module(
  File "benchmark_ait.py", line 210, in compile_module
    mod = compile_model(y, target, "./tmp", model_name)
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/compiler.py", line 176, in compile_model
    compiler.transform.profile(
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/transform/profile.py", line 60, in profile
    paths = func._attrs["exec_path"].keys()
KeyError: 'exec_path'
```

**Comment by antinucleon** [comment]
Sorry for the break. It is related to https://github.com/facebookincubator/AITemplate/issues/22 and https://github.com/facebookincubator/AITemplate/pull/20

We are working on a fix now.
