### ISSUE TITLE
[Feature Request] support for stable-diffusion-2-depth

### ISSUE THREAD

**Issue by apivovarov** [facebookincubator/AITemplate#285]
I tried to use existing example [05_stable_diffusion](https://github.com/facebookincubator/AITemplate/tree/main/examples/05_stable_diffusion) to [compile stable-diffusion-2-depth](https://huggingface.co/stabilityai/stable-diffusion-2-depth).
I updated `scripts/download_pipeline.py` to get pre-trained `stabilityai/stable-diffusion-2-depth`.
All other files were used as-is.
The compilation failed with error - `ConstantTensor's maximum size is not equal to len(data)! Got len(data)=28800, but expected at least 23040 bytes. `
```
Culled cutlass_tensorop_gz884hemm_64x32_8x4_n_rs_u_align1 from manifest
Culled cutlass_tensorop_gz884hemm_32x64_8x4_n_rs_u_align1 from manifest
Traceback (most recent call last):
  File "scripts/compile.py", line 97, in <module>
    compile_diffusers()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "scripts/compile.py", line 75, in compile_diffusers
    compile_unet(
  File "/home/ubuntu/workspace/AITemplate/examples/05_stable_diffusion/src/compile_lib/compile_unet.py", line 88, in compile_unet
    compile_model(Y, target, "./tmp", "UNet2DConditionModel", constants=params_ait)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/aitemplate/compiler/compiler.py", line 166, in compile_model
    compiler.transform.bind_constants(graph, constants)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/aitemplate/compiler/transform/bind_constants.py", line 53, in bind_constants
    tensor._bind_data(_TorchConstantTensorData(constants[name]))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/aitemplate/compiler/base.py", line 539, in _bind_data
    raise ValueError(
ValueError: ConstantTensor's maximum size is not equal to len(data)! Got len(data)=28800, but expected at least 23040 bytes. Check that the ConstantTensor's size and dtype are correct.
```

**Comment by NotNANtoN** [comment]
The depth model has a different input shape that you need to adapt. I think it has one more channel for the depth at the input of the unet
