### ISSUE TITLE
Cannot run demo_img2img for shape 512x768 

### ISSUE THREAD

**Issue by lizhengwei1992** [facebookincubator/AITemplate#291]
Env:
A100
cuda 11.6

I follow the readme of `examples/05_stable_diffusion`, if works well for 512x512. 
when change the shape to 512x768，I rerun the script `python3 scripts/compile.py --width 512 --height 768`, it succed .
but  `python3 scripts/demo_img2img.py --width 512 --height 768`,get error:
`[20:10:59] model_container.cu:64: Init AITemplate Runtime with 1 concurrency
  0%|                                                                                                                                              | 0/37 [00:00<?, ?it/s][20:11:14] model_interface.cu:169: Error: [SetValue] Dimension got value out of bounds; expected value to be in [96, 96], but got 64
  0%|                                                                                                                                              | 0/37 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "scripts/demo_img2img.py", line 77, in <module>
    run()
  File "/root/miniconda3/envs/ait/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/root/miniconda3/envs/ait/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/root/miniconda3/envs/ait/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/miniconda3/envs/ait/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "scripts/demo_img2img.py", line 65, in run
    images = pipe(
  File "/root/miniconda3/envs/ait/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/zhengwei/AITemplate/examples/05_stable_diffusion/src/pipeline_stable_diffusion_img2img_ait.py", line 356, in __call__
    noise_pred = self.unet_inference(
  File "/mnt/zhengwei/AITemplate/examples/05_stable_diffusion/src/pipeline_stable_diffusion_img2img_ait.py", line 147, in unet_inference
    exe_module.run_with_tensors(inputs, ys, graph_mode=False)
  File "/root/miniconda3/envs/ait/lib/python3.8/site-packages/aitemplate/compiler/model.py", line 535, in run_with_tensors
    outputs_ait = self.run(
  File "/root/miniconda3/envs/ait/lib/python3.8/site-packages/aitemplate/compiler/model.py", line 438, in run
    return self._run_impl(
  File "/root/miniconda3/envs/ait/lib/python3.8/site-packages/aitemplate/compiler/model.py", line 377, in _run_impl
    self.DLL.AITemplateModelContainerRun(
  File "/root/miniconda3/envs/ait/lib/python3.8/site-packages/aitemplate/compiler/model.py", line 181, in _wrapped_func
    raise RuntimeError(f"Error in function: {method.__name__}")
RuntimeError: Error in function: AITemplateModelContainerRun`

how to build new shape for img2img piplie ?

**Comment by ipiszy** [comment]
Hi @lizhengwei1992 , this may need more debugging. It looks that AIT input tensor shapes are not set properly for some reason. cc @terrychenism who may have more ideas.
Could you help apply https://github.com/facebookincubator/AITemplate/pull/305 and run `python3 scripts/demo_img2img.py` to print more debug info?

**Comment by terrychenism** [comment]
We didn't update img2img for SD2.0+, but it should be easy to have. Please try 512x512 first.

**Comment by lizhengwei1992** [comment]
> We didn't update img2img for SD2.0+, but it should be easy to have. Please try 512x512 first.

Thanks !
I have already run demo_img2img  for SDv1/SDV2 successly on shape 512x512 / 768x768。
I want it to work on non-square shapes as described in `examples/05_stable_diffusion/README` :
`For img2img model we only support fix input 512x768 by default, stay tuned for dynamic shape support
`

**Comment by terrychenism** [comment]
did you compile the model using 512x768?

**Comment by lizhengwei1992** [comment]
> did you compile the model using 512x768?

Yes, use this script :
`python3 scripts/compile.py --width 512 --height 768`

then,  run 
`python3 scripts/demo_img2img.py --width 512 --height 768`;

got error:

`Error: [SetValue] Dimension got value out of bounds; expected value to be in [96, 96], but got 64 0%| `

I also clean original compiled files and rerun it, it doesn't help .

**Comment by lizhengwei1992** [comment]
I made a stupid mistake ... ...
 when I resize the init image to 512x768, I reversed width and height. Now it works well for shape 512x768.
