### ISSUE TITLE
Cannot generate picture with size other than 512*512

### ISSUE THREAD

**Issue by MetisDeveloper** [facebookincubator/AITemplate#304]
environment
Ubuntu 20.04.5 LTS
cuda 11.6
Python 3.8.10
A100
SD2.1

I want it to work with values other than 512. I also want it to work on non-square shapes.

the code
```
from diffusers import EulerAncestralDiscreteScheduler
from aitemplate.utils.import_path import import_parent
from src.pipeline_stable_diffusion_ait import StableDiffusionAITPipeline
import torch

import_parent(filepath=__file__, level=1)
model_id = "/dir/layer_merged-v1.5"
scheduler = EulerAncestralDiscreteScheduler.from_config(model_id, subfolder="scheduler")
pipe = StableDiffusionAITPipeline.from_pretrained(
    model_id,
    torch_dtype=torch.float32,
    revision="fp32",
    scheduler=scheduler,
)
pipe = pipe.to("cuda")
image = pipe("1 girl, cute, school uniform", height=768, width=768).images[0]
image.save("test.png")
```
This code specifies 768 for both height and width.

error
```
Traceback (most recent call last):
  File "generate_test.py", line 17, in <module>
    image = pipe("1 girl, cute, school uniform", height=768, width=768).images[0]
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "<<base dir>>/src/pipeline_stable_diffusion_ait.py", line 363, in __call__
    noise_pred = self.unet_inference(
  File "<<base dir>>/src/pipeline_stable_diffusion_ait.py", line 136, in unet_inference
    exe_module.run_with_tensors(inputs, ys, graph_mode=False)
  File "<<home>>/.local/lib/python3.8/site-packages/aitemplate/compiler/model.py", line 535, in run_with_tensors
    outputs_ait = self.run(
  File "<<home>>/.local/lib/python3.8/site-packages/aitemplate/compiler/model.py", line 438, in run
    return self._run_impl(
  File "<<home>>/.local/lib/python3.8/site-packages/aitemplate/compiler/model.py", line 377, in _run_impl
    self.DLL.AITemplateModelContainerRun(
  File "<<home>>/.local/lib/python3.8/site-packages/aitemplate/compiler/model.py", line 181, in _wrapped_func
    raise RuntimeError(f"Error in function: {method.__name__}")
RuntimeError: Error in function: AITemplateModelContainerRun
```

Thank you.

**Comment by asynclee** [comment]
Hello @MetisDeveloper 
As far as I know, AITemplate does not yet support dynamic shape for input tensor.
Because of that, if you want to create an image of a different size, you need to proceed with that size in the compile step.
ex. 768x768 size, 
python3 compile.py --height 768 --width 768
You need to do this to compile for that size.

**Comment by ipiszy** [comment]
Thanks @asynclee , yeah this is correct.

To provide more context: AIT has limited support for dynamic shapes, but the fused multi-head attention kernel used by SD doesn't support dynamic shapes for now.
