### ISSUE TITLE
[Stable Diffusion][Bug] Compiling for non-square shape errors out

### ISSUE THREAD

**Issue by Stax124** [facebookincubator/AITemplate#345]
The compiler throws an error when attempting to build an engine with shape 912x512, while 512x512 was compiled without a problem.

**Traceback:**
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/applications.py", line 118, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.8/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/workspaces/voltaML/api/routes/generate.py", line 126, in generate_aitemplate
    await cluster.build_aitemplate(request)
  File "/workspaces/voltaML/core/cluster.py", line 178, in build_aitemplate
    await best_gpu.build_aitemplate_engine(request)
  File "/workspaces/voltaML/core/gpu.py", line 400, in build_aitemplate_engine
    raise err
  File "/workspaces/voltaML/core/thread.py", line 42, in run
    self._return = target(*self._args, **self._kwargs)  # type: ignore
  File "/workspaces/voltaML/core/gpu.py", line 391, in build
    compile_diffusers(
  File "/workspaces/voltaML/core/aitemplate/scripts/compile.py", line 69, in compile_diffusers
    compile_unet(
  File "/workspaces/voltaML/core/aitemplate/src/compile_lib/compile_unet.py", line 83, in compile_unet
    Y = ait_mod(latent_model_input_ait, timesteps_ait, text_embeddings_pt_ait)
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/frontend/nn/module.py", line 390, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspaces/voltaML/core/aitemplate/src/modeling/unet_2d_condition.py", line 240, in forward
    sample = upsample_block(
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/frontend/nn/module.py", line 390, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspaces/voltaML/core/aitemplate/src/modeling/unet_blocks.py", line 541, in forward
    hidden_states = ops.concatenate()(
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/ops/tensor/concatenate.py", line 125, in __call__
    output_shape = self._infer_shapes(inputs, dim)
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/ops/tensor/concatenate.py", line 100, in _infer_shapes
    raise RuntimeError(
RuntimeError: tensors expected to have the same dimensions except concat_dim! dim: 1, shape1: {'depth': 0, 'name': None, 'nop': False, 'values': [30]}, shape2: {'depth': 0, 'name': None, 'nop': False, 'values': [29]}, inputs: [{ 'check_nan_and_inf': False,
  'check_outputs': False,
  'constant_folding_output_idx': None,
  'data': None,
  'depth': 321,
  'dst_ops': [None],
  'dtype': 'float16',
  'external_tensor': None,
  'has_output_aliases': False,
  'is_input': False,
  'is_internal_constant': False,
  'is_output': False,
  'is_param': False,
  'is_view_of': None,
  'name': None,
  'nop': False,
  'offset': None,
  'shape': [ {'depth': 0, 'name': None, 'nop': False, 'values': [2]},
             {'depth': 0, 'name': None, 'nop': False, 'values': [30]},
             {'depth': 0, 'name': None, 'nop': False, 'values': [16]},
             {'depth': 0, 'name': None, 'nop': False, 'values': [1280]}],
  'src_ops': [None],
  'value': None}, { 'check_nan_and_inf': False,
  'check_outputs': False,
  'constant_folding_output_idx': None,
  'data': None,
  'depth': 241,
  'dst_ops': [None, None],
  'dtype': 'float16',
  'external_tensor': None,
  'has_output_aliases': False,
  'is_input': False,
  'is_internal_constant': False,
  'is_output': False,
  'is_param': False,
  'is_view_of': None,
  'name': None,
  'nop': False,
  'offset': None,
  'shape': [ {'depth': 0, 'name': None, 'nop': False, 'values': [2]},
             {'depth': 0, 'name': None, 'nop': False, 'values': [29]},
             {'depth': 0, 'name': None, 'nop': False, 'values': [16]},
             {'depth': 0, 'name': None, 'nop': False, 'values': [1280]}],
  'src_ops': [None],
  'value': None}]
```

**System:**
Host OS: Kubuntu 22.04.2 LTS
Running In Docker: yes
AITemplate version (pip): 0.1.dev1
PyTorch: 1.13.1
GPU: Nvidia RTX3050
Driver version: 525.85.12
CUDA version: 12.0

**Comment by terrychenism** [comment]
can you make inputs divisible by 32?

**Comment by Stax124** [comment]
> can you make inputs divisible by 32 and re-run it?

Same error, even with 512x928, i will try to debug that more tomorrow, if I stumble on more helpful data, I will let you know

**Comment by Stax124** [comment]
@terrychenism according to my testing, it seems like the required step is 64.

I was able to compile a 512x768 model without a problem. It would be great if it was mentioned somewhere.
https://github.com/facebookincubator/AITemplate/blob/9fdf6f2cd380209dbaa6c26c358d9949f2a899dd/examples/05_stable_diffusion/scripts/compile.py#L60-L61

I will create a PR with the values changed to the required ones,

Have a nice day and thanks for making this project available to the public.
