### ISSUE TITLE
Stable Diffusion Example Installation Not Working - SyntaxError

### ISSUE THREAD

**Issue by kennethgoodman** [facebookincubator/AITemplate#4]
reproduce on google colab:
```
!git clone /content/AITemplate https://github.com/facebookincubator/AITemplate.git
%cd /content/AITemplate/python
!python setup.py bdist_wheel
!pip install dist/*.whl
%cd /content/AITemplate/examples/05_stable_diffusion
from pipeline_stable_diffusion_ait import StableDiffusionAITPipeline
```

Error:
```
Traceback (most recent call last):

  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File ["<ipython-input-46-f3821b1f7a5a>"](https://localhost:8080/#), line 2, in <module>
    from pipeline_stable_diffusion_ait import StableDiffusionAITPipeline

  File "/content/AITemplate/examples/05_stable_diffusion/pipeline_stable_diffusion_ait.py", line 22, in <module>
    from aitemplate.compiler import Model

  File "/usr/local/lib/python3.7/dist-packages/aitemplate/__init__.py", line 19, in <module>
    from . import backend, compiler, frontend, testing, utils

  File "/usr/local/lib/python3.7/dist-packages/aitemplate/backend/__init__.py", line 18, in <module>
    from . import (  # noqa

  File "/usr/local/lib/python3.7/dist-packages/aitemplate/backend/backend_spec.py", line 25, in <module>
    from ..compiler.ops.common.epilogue import FuncEnum

  File "/usr/local/lib/python3.7/dist-packages/aitemplate/compiler/__init__.py", line 15, in <module>
    from . import base, ops, tensor_accessor, transform

  File "<fstring>", line 1
    (len(self.src_ops())=)
                        ^
SyntaxError: invalid syntax
```

**Comment by antinucleon** [comment]
Please check Python version. It requires > 3.8, also please clone with submodules

```
git clone --recursive https://github.com/facebookincubator/AITemplate
cd python
python setup.py bdist_wheel
pip install dist/*.whl --force-reinstall

```

**Comment by kennethgoodman** [comment]
Yes, thank you, I needed 3.8, I also needed cuda-11.6, 11.2 wasn't working. 

You can see results here: https://colab.research.google.com/gist/kennethgoodman/f42df87eda4bf427c3d3731f73e43b6f/fbaitemplate-stable-diffusion.ipynb

Note that image quality isn't great for initial test. Could it be a different encoder? Will play around to see

**Comment by antinucleon** [comment]
Thanks for work it out. T4 is not officially supported. We don't have T4 in cluster so we didn't measure correctness of GPU kernels for T4. We have a few kernels using `cp.async` which is required for SM80 GPU (A100/A30, RTX-30).
