### ISSUE TITLE
stable diffusion example in docker error

### ISSUE THREAD

**Issue by ericlormul** [facebookincubator/AITemplate#5]
running in docker using downloaded diffuser checkpoint. See snippet below:

```
  pipe = StableDiffusionAITPipeline.from_pretrained(
      "./stable-diffusion-v1-4",
      revision="fp16",
      torch_dtype=torch.float16,
      # use_auth_token=token,
  ).to("cuda")
```
Error outputs:

```
root@3c9c833e62c7:/AITemplate# CUUDA_VISIBLE_DEVICES=7 python3 my_exampels/05_stable_diffusion/demo.py
INFO:aitemplate.testing.detect_target:Set target to CUDA
ftfy or spacy is not installed using BERT BasicTokenizer instead of ftfy.
{'trained_betas'} was not found in config. Values will be initialized to default values.
Traceback (most recent call last):
  File "my_exampels/05_stable_diffusion/demo.py", line 46, in <module>
    run()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "my_exampels/05_stable_diffusion/demo.py", line 29, in run
    pipe = StableDiffusionAITPipeline.from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/diffusers/pipeline_utils.py", line 391, in from_pretrained
    model = pipeline_class(**init_kwargs)
  File "/AITemplate/my_exampels/05_stable_diffusion/pipeline_stable_diffusion_ait.py", line 89, in __init__
    self.clip_ait_exe = self.init_ait_module(
  File "/AITemplate/my_exampels/05_stable_diffusion/pipeline_stable_diffusion_ait.py", line 104, in init_ait_module
    mod = Model(os.path.join(workdir, model_name, "test.so"))
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/model.py", line 212, in __init__
    self.DLL = self._DLLWrapper(lib_path, num_runtimes)
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/model.py", line 169, in __init__
    self.DLL = ctypes.cdll.LoadLibrary(lib_path)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: tmp/CLIPTextModel/test.so: cannot open shared object file: No such file or directory
Exception ignored in: <function Model.__del__ at 0x7fcbb1d8b940>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/model.py", line 255, in __del__
    self.close()
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/model.py", line 259, in close
    for ptr in list(self._allocated_ait_data):
AttributeError: 'Model' object has no attribute '_allocated_ait_data'
```

**Comment by terrychenism** [comment]
```
OSError: tmp/CLIPTextModel/test.so: cannot open shared object file: No such file or directory
```
you need to compile the model first by running: 
```
python3 examples/05_stable_diffusion/compile.py
```
