### ISSUE TITLE
RuntimeError: Error in function: AITemplateModelContainerRun

### ISSUE THREAD

**Issue by swayam1998** [facebookincubator/AITemplate#51]
I have been following installation steps and trying to run the stable diffusion template.
But running all the commands, I face issues after this.

CMD: 
python3 examples/05_stable_diffusion/demo.py --token ACCESS_TOKEN
Error:
Traceback (most recent call last):
  File "examples/05_stable_diffusion/demo.py", line 46, in <module>
    run()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "examples/05_stable_diffusion/demo.py", line 37, in run
    image = pipe(prompt).images[0]
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/AITemplate/examples/05_stable_diffusion/pipeline_stable_diffusion_ait.py", line 328, in __call__
    noise_pred = self.unet_inference(
  File "/AITemplate/examples/05_stable_diffusion/pipeline_stable_diffusion_ait.py", line 123, in unet_inference
    exe_module.run_with_tensors(inputs, ys, graph_mode=False)
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/model.py", line 483, in run_with_tensors
    outputs_ait = self.run(
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/model.py", line 438, in run
    return self._run_impl(
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/model.py", line 377, in _run_impl
    self.DLL.AITemplateModelContainerRun(
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/model.py", line 192, in _wrapped_func
    raise RuntimeError(f"Error in function: {method.__name__}")
RuntimeError: Error in function: AITemplateModelContainerRun

I cannot find any way to solve this.

**Comment by antinucleon** [comment]
Looks like a mismatch between compiled model and input. I guess you want to generate larger image but didn’t compile it correctly.

**Comment by swayam1998** [comment]
Yes. That was the issue. Thanks
