### ISSUE TITLE
Issues running benchmarking tools for Resnet, ViT on RTX 2080

### ISSUE THREAD

**Issue by outtanames** [facebookincubator/AITemplate#583]
Attempting to run the 04_vit benchmarking tool hits an error when trying to load an op instance for one of the conv ops.
```
Traceback (most recent call last):
  File "./benchmark_ait.py", line 186, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "./benchmark_ait.py", line 179, in main
    compile_vit(model_name, bs, use_fp16_acc=use_fp16_acc)
  File "./benchmark_ait.py", line 90, in compile_vit
    exe_module = compile_model(
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/compiler.py", line 298, in compile_model
    file_pairs = backend.codegen.gen_function_src(graph, workdir, test_name)
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/backend/codegen.py", line 116, in gen_function_src
    fo.write(func.gen_function())
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/ops/conv/conv2d.py", line 758, in gen_function
    return func(
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/backend/cuda/conv2d/conv2d_bias_few_channels.py", line 94, in conv2d_bias_few_channels_gen_function
    return cba.gen_function(
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/backend/cuda/conv2d/common_conv2d_bias_activation.py", line 51, in gen_function
    return common.gen_function(
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/backend/cuda/conv2d/common.py", line 775, in gen_function
    emitted_instance = f_emit_instance(op_instance[value])
KeyError: ''
```

Any troubleshooting tips?

**Comment by muchulee8** [comment]
Could you share what the cutlass/cuda versions you're on?

**Comment by outtanames** [comment]
I'm on CUDA 12.1

**Comment by ioeddk** [comment]
I'm having exactly the same problem. Either in the container or build in WSL. CUDA version 11.7.

**Comment by tenpercent** [comment]
`KeyError: ''` typically means the profiler has crashed
for more introspection during debugging, try setting env `LOGLEVEL=DEBUG`, then inspecting the logs

my wild guess would be RTX 2080 is sm75 and we need sm80 for this example

**Comment by ioeddk** [comment]
It seems like I identified the problem. First, in `resnet.py` I changed `nn.Conv2dBiasReluFewChannels` to `nn.Conv2dBiasRelu`. This solves the "key error" problem, but is causing this error: 
```[18:32:46] model_interface.cu:122: Error: SetConstant did not receive correct number of bytes for unbound constant stem_conv1_weight: expected 18816 but got 25088. Check that the provided tensor's shape is correct.
Traceback (most recent call last):
  File "/home/ioeddk/GitHub/AIT-demo/01_resnet-50/benchmark_ait.py", line 142, in <module>
    main()
  File "/home/ioeddk/venv/ait/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ioeddk/venv/ait/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ioeddk/venv/ait/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ioeddk/venv/ait/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ioeddk/GitHub/AIT-demo/01_resnet-50/benchmark_ait.py", line 138, in main
    benchmark("resnet50", batch_size, graph_mode=use_graph)
  File "/home/ioeddk/GitHub/AIT-demo/01_resnet-50/benchmark_ait.py", line 81, in benchmark
    mod.set_many_constants_with_tensors(cuda_params)
  File "/home/ioeddk/venv/ait/lib/python3.10/site-packages/aitemplate/compiler/model.py", line 809, in set_many_constants_with_tensors
    self.set_many_constants(ait_tensors)
  File "/home/ioeddk/venv/ait/lib/python3.10/site-packages/aitemplate/compiler/model.py", line 760, in set_many_constants
    self.DLL.AITemplateModelContainerSetManyConstants(
  File "/home/ioeddk/venv/ait/lib/python3.10/site-packages/aitemplate/compiler/model.py", line 181, in _wrapped_func
    raise RuntimeError(f"Error in function: {method.__name__}")
RuntimeError: Error in function: AITemplateModelContainerSetManyConstants```
Then I changed the line 147 `conv_w = torch.zeros((64, 7, 7, 4))` to `conv_w = torch.zeros((64, 7, 7, 3))` then the example finishs running. I think this is probably because the `FewChannels` kernels cause the "profiler to crash" problem as mentioned above, on SM75 GPUs .
