### ISSUE TITLE
RuntimeError: Tensor conv2d_bias_64_1 not in outputs for op avg_pool2d_53

### ISSUE THREAD

**Issue by howellyoung-s** [facebookincubator/AITemplate#60]
## summary
I use AITemplate to re-construct a diffusion model which is slightly different than the one in examples, but error occurs while call compile_model().
Since it says some AvgPooling op is not in the outputs of some conv2d_bias op, so I just show the only related code as below where 'AvgPooling' is only used by the 'Resample' module.
I review the forward implementation of 'ResidualBlock', but no clue can be found.

## code1
`class Resample(nn.Module):

    def __init__(self, in_dim, out_dim, scale_factor, use_conv=False):
        assert scale_factor in [0.5, 1.0, 2.0]
        super(Resample, self).__init__()
        self.in_dim = in_dim
        self.out_dim = out_dim
        self.scale_factor = scale_factor
        self.use_conv = use_conv

        # layers
        if scale_factor == 2.0:
            self.resample = nn.Sequential(
                nn.Upsampling2d(scale_factor=scale_factor, mode='nearest'),
                nn.Conv2dBias(in_dim, out_dim, 3, 1, padding=1) if use_conv else nn.Identity())
        elif scale_factor == 0.5:
            if use_conv:
                self.resample = nn.Conv2dBias(in_dim, out_dim, 3, stride=2, padding=1) 
            else:
                self.resample = nn.AvgPool2d(kernel_size=2, stride=2, padding=0)
        else:
            self.resample = nn.Identity()
    
    def forward(self, x):
        return self.resample(x)

class SiLU(nn.Module):
    def __init__(self) -> None:
        super(SiLU, self).__init__()
        self.silu = ops.silu
    
    def forward(self, x):
        out = self.silu(x)
        return out

class ResidualBlock(nn.Module):

    def __init__(self, in_dim, embed_dim, out_dim, use_scale_shift_norm=True,
                 scale_factor=1.0, dropout=0.0):
        super(ResidualBlock, self).__init__()
        self.in_dim = in_dim
        self.embed_dim = embed_dim
        self.out_dim = out_dim
        self.use_scale_shift_norm = use_scale_shift_norm
        self.scale_factor = scale_factor

        # layers
        self.layer1 = nn.ModuleList([
            nn.GroupNorm(32, in_dim),
            SiLU(),
            nn.Conv2dBias(in_dim, out_dim, 3, 1, padding=1)])
        self.resample = Resample(in_dim, in_dim, scale_factor, use_conv=False)
        self.embedding = nn.Sequential(
            SiLU(),
            nn.Linear(embed_dim, out_dim * 2 if use_scale_shift_norm else out_dim))
        self.layer2 = nn.ModuleList([
            nn.GroupNorm(32, out_dim),
            SiLU(),
            nn.Dropout(dropout),
            nn.Conv2dBias(out_dim, out_dim, 3, 1, padding=1)])
        self.shortcut = nn.Identity() if in_dim == out_dim else nn.Conv2dBias(in_dim, out_dim, 1, 1)

    
    def forward(self, x, e):
        hidden_states = x

        hidden_states = self.layer1[0](hidden_states)
        hidden_states_0 = self.layer1[1](hidden_states)
        x = self.resample(x) # 
        hidden_states_1 = self.resample(hidden_states_0)
        hidden_states_2 = self.layer1[2](hidden_states_1) #
        e = self.embedding(e) #
        bs, dim = get_shape(e)
        e = ops.reshape()(e, [bs, 1, 1, dim])

        hidden_states = hidden_states_2 + e
        hidden_states = self.layer2[0](hidden_states)
        hidden_states = self.layer2[1](hidden_states)
        hidden_states = self.layer2[2](hidden_states)
        hidden_states = self.layer2[3](hidden_states)

        x = self.shortcut(x)
        out = hidden_states + x
        return out`

## code2
`def rebuild_net(use_fp16_acc=False, convert_conv_to_gemm=False):

    ...
    net = pytorch_model().cuda().half() # use fp16
    net.eval()
    ait_net = AITUpsampler()
    ait_net.name_parameter_tensor()
    mapped_params = map_pt_params(ait_net, net)

    batch_size = 4
    hh = 256
    ww = 256
    cc = 3
    x0 = Tensor(
        [batch_size, hh, ww, cc], name="input0", is_input=True
    )
    t = Tensor([batch_size, upsampler256_config['dim']], name="input1", is_input=True)
    y = Tensor([batch_size, upsampler256_config['y_dim']], name="input2", is_input=True)
    concat = Tensor(
        [batch_size, hh, ww, cc], name="input3", is_input=True
    )

    Y_out = ait_net(x0, t, y, concat)
    target = detect_target(
        use_fp16_acc=use_fp16_acc, convert_conv_to_gemm=convert_conv_to_gemm
    )

    compile_model(Y_out, target, "./tmp", "AIT_UPSAMPLER256", constants=mapped_params)`

## Error
`AIT output_0 shape: [4, 256, 256, 3]
Traceback (most recent call last):
  File "convert2ait_upsampler256.py", line 106, in <module>
    compile_net(True, True)
  File "convert2ait_upsampler256.py", line 95, in compile_net
    graph = apply_optimizations(Y_out)
  File "convert2ait_upsampler256.py", line 47, in apply_optimizations
    graph = compiler.transform.optimize_graph(graph, "./tmp")
  File "/home/pai/envs/zero/lib/python3.8/site-packages/aitemplate/compiler/transform/optimize_graph.py", line 84, in optimize_graph
    sorted_graph = func(sorted_graph, workdir)
  File "/home/pai/envs/zero/lib/python3.8/site-packages/aitemplate/compiler/transform/fuse_permute_bmm.py", line 219, in fuse_permute_bmm
    fused, sorted_graph = _fuse_permute_bmm_ops(
  File "/home/pai/envs/zero/lib/python3.8/site-packages/aitemplate/compiler/transform/fuse_permute_bmm.py", line 171, in _fuse_permute_bmm_ops
    return (fused, sanitize_sorted_graph(new_sorted_graph))
  File "/home/pai/envs/zero/lib/python3.8/site-packages/aitemplate/compiler/transform/transform_utils.py", line 272, in sanitize_sorted_graph
    check_graph_validity(new_sorted_graph, raiseError=True)
  File "/home/pai/envs/zero/lib/python3.8/site-packages/aitemplate/compiler/transform/transform_utils.py", line 69, in check_graph_validity
    valid = handleError(
  File "/home/pai/envs/zero/lib/python3.8/site-packages/aitemplate/compiler/transform/transform_utils.py", line 40, in handleError
    raise RuntimeError(msg)
RuntimeError: Tensor conv2d_bias_64_1 not in outputs for op avg_pool2d_53
`

**Comment by hlu1** [comment]
Can you try commenting out this line: https://github.com/facebookincubator/AITemplate/blob/main/python/aitemplate/compiler/transform/remove_no_ops.py#L163? I think you hit a bug in this pass. Also, are there expand ops in your model?

**Comment by ioeddk** [comment]
Is there an update on this problem? I'm facing a similar problem and the line to be commented off above is an parenthesis. So in the function `_is_compatible_with_broadcasting` we just try simply return True?

**Comment by hlky** [comment]
Ran into a similar issue while working on RRDBNet.

```
    def forward(self, x):
        x1 = self.lrelu(self.conv1(x))
        x2 = self.lrelu(self.conv2(self.cat((x, x1), 3)))
        x3 = self.lrelu(self.conv3(self.cat((x, x1, x2), 3)))
        x4 = self.lrelu(self.conv4(self.cat((x, x1, x2, x3), 3)))
        x5 = self.conv5(self.cat((x, x1, x2, x3, x4), 3))
        # Empirically, we use 0.2 to scale the residual for better performance
        out = x5 * 0.2 + x
        return out
```

When using `ops.concatenate` directly it appears that the next conv layers are not used, only the first is used.

AIT dump (dump_ait_to_py):
```
    def model(self):
        conv2d_bias_0_0 = ops.conv2d_bias(dilate=1, group=1, pad=1, stride=1)(self.rdb_input, self.conv1_weight, self.conv1_bias)

        # Set outputs

        # End of setting outputs
        return 
```

Marking as `is_input` resolves the issue.
```
def cat(self, tensors, dim):
        out = ops.concatenate()(tensors, dim)
        out._attrs['is_input'] = True
        return out
```

So it seems there is some issue when part of the graph does not use the input tensor directly.
