### ISSUE TITLE
python scripts/compile.py error

### ISSUE THREAD

**Issue by baimingl** [facebookincubator/AITemplate#613]
ake: Leaving directory '/data/bml/tool/AITemplate/examples/05_stable_diffusion/tmp/profiler'

2023-04-24 12:55:25,551 INFO <aitemplate.backend.builder> make stderr:

/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^ 
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^ 
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
make: *** [Makefile_f4b2dcf0579ea02d7f3e592d4475e56800bce1b6:6: gemm_rcr_bias_permute/gemm_rcr_bias_permute_30d331b46ca1799ff6ead39ab17266cdc17ffea8_3] Error 1
make: *** Waiting for unfinished jobs....
/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^ 
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^ 
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
make: *** [Makefile_f4b2dcf0579ea02d7f3e592d4475e56800bce1b6:12: gemm_rcr_bias_gelu/gemm_rcr_bias_gelu_9e46850d5286ecc7e078b5b7f76afbcac62967b4_3] Error 1
/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^ 
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^ 
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
make: *** [Makefile_f4b2dcf0579ea02d7f3e592d4475e56800bce1b6:9: gemm_rcr_bias_add/gemm_rcr_bias_add_9e46850d5286ecc7e078b5b7f76afbcac62967b4_3] Error 1

Traceback (most recent call last):
  File "scripts/compile.py", line 99, in <module>
    compile_diffusers()
  File "/data/usr/local/python3-8-10/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/data/usr/local/python3-8-10/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/data/usr/local/python3-8-10/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/usr/local/python3-8-10/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "scripts/compile.py", line 65, in compile_diffusers
    compile_clip(
  File "/data/bml/tool/AITemplate/examples/05_stable_diffusion/src/compile_lib/compile_clip.py", line 113, in compile_clip
    compile_model(Y, target, "./tmp", "CLIPTextModel", constants=params_ait)
  File "/data/usr/local/python3-8-10/lib/python3.8/site-packages/aitemplate/compiler/compiler.py", line 272, in compile_model
    compiler.transform.profile(
  File "/data/usr/local/python3-8-10/lib/python3.8/site-packages/aitemplate/compiler/transform/profile.py", line 89, in profile
    compile_engine.make_profilers(generated_profilers, profiler_dir)
  File "/data/usr/local/python3-8-10/lib/python3.8/site-packages/aitemplate/backend/builder.py", line 821, in make_profilers
    _run_make_cmds(
  File "/data/usr/local/python3-8-10/lib/python3.8/site-packages/aitemplate/backend/builder.py", line 182, in _run_make_cmds
    raise RuntimeError("Build has failed.")
RuntimeError: Build has failed.

**Comment by tenpercent** [comment]
could you try compiling with env `LOGLEVEL=DEBUG` to see what's the c++ compilation error root cause is?
