### ISSUE TITLE
recompile stable diffusion for 1024x1024

### ISSUE THREAD

**Issue by Suhail** [facebookincubator/AITemplate#63]
How might one do this? Currently it only works for 512x512.

**Comment by Suhail** [comment]
I just found this comment: https://github.com/facebookincubator/AITemplate/issues/13#issuecomment-1267310976

**Comment by Suhail** [comment]
Here's what I tried:
![CleanShot 2022-10-29 at 07 58 03](https://user-images.githubusercontent.com/66225/198838446-cef6f99a-2e9c-43f6-a278-3f1f9cf68960.png)

![CleanShot 2022-10-29 at 07 59 33](https://user-images.githubusercontent.com/66225/198838536-8d52c54c-c7df-4802-971f-394bf37c4fdb.png)


Is there something I need to do with batch_size differently?

**Comment by Suhail** [comment]
Managed to get here:
```INFO:aitemplate.testing.detect_target:Set target to CUDA
Fetching 15 files: 100%|████████████████████████████████████████████████████████████| 15/15 [00:00<00:00, 37560.93it/s]
ftfy or spacy is not installed using BERT BasicTokenizer instead of ftfy.
[20:37:26] ./tmp/CLIPTextModel/model-generated.h:275: Init AITemplate Runtime.
[20:37:26] ./tmp/UNet2DConditionModel/model-generated.h:3334: Init AITemplate Runtime.
[20:37:26] ./tmp/AutoencoderKL/model-generated.h:678: Init AITemplate Runtime.
  0%|                                                                                           | 0/51 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "demo.py", line 46, in <module>
    run()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "demo.py", line 37, in run
    image = pipe(prompt).images[0]
  File "/usr/lib/python3/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/AITemplate/examples/05_stable_diffusion/pipeline_stable_diffusion_ait.py", line 328, in __call__
    noise_pred = self.unet_inference(
  File "/home/ubuntu/AITemplate/examples/05_stable_diffusion/pipeline_stable_diffusion_ait.py", line 124, in unet_inference
    noise_pred = ys[0].permute((0, 3, 1, 2)).float()
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**Comment by pveerina** [comment]
I was able to get this working by doing the following (I'm on an A100 40gb).

- Update compile.py to have 128 width/height and unet batch size of 1 and recompile the pipeline
```
diff --git a/examples/05_stable_diffusion/compile.py b/examples/05_stable_diffusion/compile.py
index 513df5b..b4eb9f8 100644
--- a/examples/05_stable_diffusion/compile.py
+++ b/examples/05_stable_diffusion/compile.py
@@ -339,19 +339,21 @@ def compile_diffusers(token, batch_size, img2img=False, use_fp16_acc=True, conve
         use_auth_token=access_token,
     ).to("cuda")

-    width = 96 if img2img else 64
+    width = 128
+    height = 128

     # CLIP
     compile_clip(batch_size=batch_size, use_fp16_acc=use_fp16_acc, convert_conv_to_gemm=convert_conv_to_gemm)
     # UNet
     compile_unet(
-        batch_size=batch_size * 2,
+        batch_size=batch_size,
         ww=width,
+        hh=height,
         use_fp16_acc=use_fp16_acc,
         convert_conv_to_gemm=convert_conv_to_gemm,
     )
     # VAE
-    compile_vae(batch_size=batch_size, width=width, use_fp16_acc=use_fp16_acc, convert_conv_to_gemm=convert_conv_to_gemm)
+    compile_vae(batch_size=batch_size, width=width, height=height, use_fp16_acc=use_fp16_acc, convert_conv_to_gemm=convert_conv_to_gemm)
```

- Split the unet inference step in `pipeline_stable_diffusion_ait.py` into two steps since the compiled batch size is 1 
```
diff --git a/examples/05_stable_diffusion/pipeline_stable_diffusion_ait.py b/examples/05_stable_diffusion/pipeline_stable_diffusion_ait.py
index 5234117..94ee46a 100644
--- a/examples/05_stable_diffusion/pipeline_stable_diffusion_ait.py
+++ b/examples/05_stable_diffusion/pipeline_stable_diffusion_ait.py
@@ -106,23 +106,45 @@ class StableDiffusionAITPipeline(StableDiffusionPipeline):

     def unet_inference(self, latent_model_input, timesteps, encoder_hidden_states):
         exe_module = self.unet_ait_exe
-        timesteps_pt = timesteps.expand(latent_model_input.shape[0])
-        inputs = {
-            "input0": latent_model_input.permute((0, 2, 3, 1))
+        latent_model_input_0 = torch.unsqueeze(latent_model_input[0], dim=0)
+        latent_model_input_1 = torch.unsqueeze(latent_model_input[1], dim=0)
+        timesteps_0 = timesteps.expand(latent_model_input_0.shape[0])
+        timesteps_1 = timesteps.expand(latent_model_input_1.shape[0])
+        encoder_hidden_states_0 = torch.unsqueeze(encoder_hidden_states[0], dim=0)
+        encoder_hidden_states_1 = torch.unsqueeze(encoder_hidden_states[1], dim=0)
+        ys_0 = []
+        ys_1 = []
+        num_ouputs = len(exe_module.get_output_name_to_index_map())
+        for i in range(num_ouputs):
+            shape = exe_module.get_output_maximum_shape(i)
+            ys_0.append(torch.empty(shape).cuda().half())
+            ys_1.append(torch.empty(shape).cuda().half())
+
+        inputs_0 = {
+            "input0": latent_model_input_0.permute((0, 2, 3, 1))
             .contiguous()
             .cuda()
             .half(),
-            "input1": timesteps_pt.cuda().half(),
-            "input2": encoder_hidden_states.cuda().half(),
+            "input1": timesteps_0.cuda().half(),
+            "input2": encoder_hidden_states_0.cuda().half(),
         }
-        ys = []
-        num_ouputs = len(exe_module.get_output_name_to_index_map())
-        for i in range(num_ouputs):
-            shape = exe_module.get_output_maximum_shape(i)
-            ys.append(torch.empty(shape).cuda().half())
-        exe_module.run_with_tensors(inputs, ys, graph_mode=False)
-        noise_pred = ys[0].permute((0, 3, 1, 2)).float()
-        return noise_pred
+
+        inputs_1 = {
+            "input0": latent_model_input_1.permute((0, 2, 3, 1))
+            .contiguous()
+            .cuda()
+            .half(),
+            "input1": timesteps_1.cuda().half(),
+            "input2": encoder_hidden_states_1.cuda().half(),
+        }
+
+        exe_module.run_with_tensors(inputs_0, ys_0, graph_mode=False)
+        exe_module.run_with_tensors(inputs_1, ys_1, graph_mode=False)
+
+        noise_pred_0 = ys_0[0].permute((0, 3, 1, 2)).float()
+        noise_pred_1 = ys_1[0].permute((0, 3, 1, 2)).float()
+
+        return torch.cat((noise_pred_0, noise_pred_1))

     def clip_inference(self, input_ids, seqlen=64):
         exe_module = self.clip_ait_exe
```

I haven't tried running the benchmarks and verification code included in example but generating a 1024x1024 image with 50 steps is taking ~13s on the compiled pipeline vs ~25s for the regular pytorch pipeline on my instance.

**Comment by Suhail** [comment]
Will try this tomorrow @pveerina - thank you!

**Comment by Suhail** [comment]
Confirmed this work @pveerina - thank you!

**Comment by Suhail** [comment]
@pveerina does this still work with the new v0.1.1 release? I tried it (it now defaults to batch_size of 1) but now I am getting this error again: `model_interface.cu:128: Error: [SetValue] Dimension got value out of bounds; expected value to be in [2, 2], but got 1`

I might be doing something wrong though.
