### ISSUE TITLE
Issues running AIT benchmarking tools for BERT on RTX 4080

### ISSUE THREAD

**Issue by chsungen** [facebookincubator/AITemplate#647]
Hello, 

I'm running the benchmarking tools on BERT. For the sequence length = [1,2,4,8,64,128,384], it worked well. However, if I choose sequence length = [512, 1024, 4096], it failed even on the batch size is 1. The error message is:
model_interface.cu:122: Error: Called SetConstant on bert_encoder_layer_0_attention_self_cu_length but can't find in either bound or unbound constant set
Traceback (most recent call last):
  File "/home/usr/ait/AITemplate/examples/03_bert/benchmark_ait.py", line 298, in <module>
    compile_and_benchmark()
  File "/home/usr/anaconda3/envs/ait/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/usr/anaconda3/envs/ait/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/usr/anaconda3/envs/ait/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/usr/anaconda3/envs/ait/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/usr/ait/AITemplate/examples/03_bert/benchmark_ait.py", line 284, in compile_and_benchmark
    mod = compile_module(
  File "/home/usr/ait/AITemplate/examples/03_bert/benchmark_ait.py", line 212, in compile_module
    mod.set_many_constants_with_tensors(params)
  File "/home/usr/anaconda3/envs/ait/lib/python3.10/site-packages/aitemplate/compiler/model.py", line 809, in set_many_constants_with_tensors
    self.set_many_constants(ait_tensors)
  File "/home/usr/anaconda3/envs/ait/lib/python3.10/site-packages/aitemplate/compiler/model.py", line 760, in set_many_constants
    self.DLL.AITemplateModelContainerSetManyConstants(
  File "/home/usr/anaconda3/envs/ait/lib/python3.10/site-packages/aitemplate/compiler/model.py", line 181, in _wrapped_func
    raise RuntimeError(f"Error in function: {method.__name__}")
RuntimeError: Error in function: AITemplateModelContainerSetManyConstants

Any ideal how to solve this issue? Thanks
Also if I set the sentence length == [511, 1023, 4095], it worked well... 
My cuda is 12.0

**Comment by terrychenism** [comment]
how did you set cu_length for seqlen [512, 1024, 4k]?

**Comment by aska-0096** [comment]
Same issue happened on RTX3080 with CUDA 11.6 and RTX4080 with CUDA 12.0.
Trigger this issue with simple:
python3 benchmark_ait.py
Any comment? @terrychenism
