### ISSUE TITLE
stable diffusion img2img fails

### ISSUE THREAD

**Issue by artbred** [facebookincubator/AITemplate#652]
Hi, I have an issue with stable diffusion scripts/demo_img2img.py. I complied AIT with 512x512 and I have no issues with running scripts/demo.py, however when I pass initial image 512x512 I get this error. I built docker image after 611 update (if it makes sense)

`[16:20:22] model_interface.cu:200: Error: [SetValue] Dimension got value out of bounds; expected value to be in [77, 77], but got 64.
Traceback (most recent call last):
  File "scripts/demo_img2img.py", line 73, in <module>
    run()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "scripts/demo_img2img.py", line 61, in run
    images = pipe(
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/AITemplate/examples/05_stable_diffusion/src/pipeline_stable_diffusion_img2img_ait.py", line 301, in __call__
    text_embeddings = self.clip_inference(text_input.input_ids.to(self.device))
  File "/AITemplate/examples/05_stable_diffusion/src/pipeline_stable_diffusion_img2img_ait.py", line 164, in clip_inference
    exe_module.run_with_tensors(inputs, ys, graph_mode=False)
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/model.py", line 535, in run_with_tensors
    outputs_ait = self.run(
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/model.py", line 438, in run
    return self._run_impl(
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/model.py", line 377, in _run_impl
    self.DLL.AITemplateModelContainerRun(
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/model.py", line 181, in _wrapped_func
    raise RuntimeError(f"Error in function: {method.__name__}")
RuntimeError: Error in function: AITemplateModelContainerRun`

I am using 1.5 model

**Comment by terrychenism** [comment]
should be fixed by https://github.com/facebookincubator/AITemplate/pull/654
