### ISSUE TITLE
StableDiffusion benchmark script cannot handle larger batch sizes even when compiling at size

### ISSUE THREAD

**Issue by ethansmith2000** [facebookincubator/AITemplate#685]
Was attempting to compile and benchmark at batch_size=4 but received this error, it looks like the batch size i pass when compiling should set the timesteps at that size as well such that this erorr shouldn't happen?

Traceback (most recent call last):
  File "src/benchmark.py", line 316, in <module>
    benchmark_diffusers()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "src/benchmark.py", line 297, in benchmark_diffusers
    benchmark_unet(
  File "src/benchmark.py", line 71, in benchmark_unet
    pt_ys = pt_mod(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/diffusers/models/unet_2d_condition.py", line 678, in forward
    timesteps = timesteps.expand(sample.shape[0])
RuntimeError: The expanded size of the tensor (8) must match the existing size (2) at non-singleton dimension 0.  Target sizes: [8].  Tensor sizes: [2]

**Comment by chenyang78** [comment]
cc @terrychenism

**Comment by terrychenism** [comment]
Could you please provide the command that can be used to reproduce the error?

**Comment by hlky** [comment]
After commenting 
`assert batch_size == 1, "batch size must be 1 for submodule verification"`
```
python src/benchmark.py --batch-size 2
```
will reproduce this error

The fix is very simple, [timesteps are not set according to batch size](https://github.com/facebookincubator/AITemplate/blob/334877d209b0beecc725106369581070dd8d48b1/examples/05_stable_diffusion/src/benchmark.py#L68).
Replace 
```
timesteps_pt = torch.Tensor([1, 1]).cuda().half()
```
with
```
timesteps_pt = torch.Tensor([1] * batch_size).cuda().half()
```

**Comment by aakhundov** [comment]
@ethansmith2000 could you please confirm that the fix suggested by @hlky helped resolving the issue? Thanks!
