### ISSUE TITLE
Hidden embedding size in compile_controlnet

### ISSUE THREAD

**Issue by jshph** [facebookincubator/AITemplate#730]
Hi, thanks for the great work with ControlNet support for AIT 🙏  @hlky 

I'm curious why the embedding size is 768 for [the input to compile_controlnet](https://github.com/facebookincubator/AITemplate/blob/main/examples/05_stable_diffusion/src/compile_lib/compile_controlnet.py#L74) by default? My understanding is that this takes input from CLIP output, which is 1024.

At least, that is my hypothesis for the errors I am getting:
```
[04:37:42] model_interface.cu:200: Error: [SetValue] Dimension got value out of bounds; expected value to be in [768, 768], but got 1024.
  0%|                                                                                                            | 0/20 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "scripts/demo_controlnet.py", line 143, in <module>
    run()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "scripts/demo_controlnet.py", line 130, in run
    image = pipe(
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/AITemplate/examples/05_stable_diffusion/src/pipeline_stable_diffusion_controlnet_ait.py", line 1062, in __call__
    down_block_residuals, mid_block_residual = self.controlnet_inference(
  File "/AITemplate/examples/05_stable_diffusion/src/pipeline_stable_diffusion_controlnet_ait.py", line 801, in controlnet_inference
    exe_module.run_with_tensors(inputs, ys, graph_mode=False)
...
```

I printed the tensor shape for the `text_embeddings` object, and I believe the `controlnet_inference` method expects 768 dimensional tensor and instead it gets 1024.

Just my observations; I admit to being a bit new to the rationale for dimension sizes here. If someone wouldn't mind explaining that too, I would appreciate the learning.

With all of this I am able to compile ControlNet AIT but not able to run the demo.

Many thanks in advance!

**Comment by hlky** [comment]
1024 is the size for CLIP ViT H used by SD2.x, SD1.x models use CLIP ViT L with size 768, so it appears you are attempting to run demo_controlnet.py with SD2.x model and that is causing the issue
   
  
   To resolve, either use SD1.x model (this is actually the default for controlnet scripts) or compile Controlnet module for SD2.x
   
   
   
    On 05/29/2023 5:43 AM BST Joshua Pham ***@***.***> wrote:
    
   
     
    
   
     
    
     
   Hi, thanks for the great work with ControlNet support for AIT 🙏 @hlky 
   I'm curious why the embedding size is 768 for the input to compile_controlnet by default? My understanding is that this takes input from CLIP output, which is 1024. 
   At least, that is my hypothesis for the errors I am getting: 
   [04:37:42] model_interface.cu:200: Error: [SetValue] Dimension got value out of bounds; expected value to be in [768, 768], but got 1024.
  0%|                                                                                                            | 0/20 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "scripts/demo_controlnet.py", line 143, in <module>
    run()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "scripts/demo_controlnet.py", line 130, in run
    image = pipe(
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/AITemplate/examples/05_stable_diffusion/src/pipeline_stable_diffusion_controlnet_ait.py", line 1062, in __call__
    down_block_residuals, mid_block_residual = self.controlnet_inference(
  File "/AITemplate/examples/05_stable_diffusion/src/pipeline_stable_diffusion_controlnet_ait.py", line 801, in controlnet_inference
    exe_module.run_with_tensors(inputs, ys, graph_mode=False)
...
 
   I printed the tensor shape for the text_embeddings object, and I believe the controlnet_inference method expects 768 dimensional tensor and instead it gets 1024. 
   Just my observations; I admit to being a bit new to the rationale for dimension sizes here. If someone wouldn't mind explaining that too, I would appreciate the learning. 
   With all of this I am able to compile ControlNet AIT but not able to run the demo. 
   Many thanks in advance!

**Comment by jshph** [comment]
Thanks for the quick reply!

Hint led me to realize that I accidentally operated on a cache of SD 2.x; removing my cache and recompiling got past this issue.

If you don't mind also thinking about this -- I am encountering a similar issue with VAE:
```
 Error: [SetValue] Dimension got value out of bounds; expected value to be in [48, 48], but got 64.
```
But I am not finding anywhere that VAE hidden dimension should be 48? All SD versions seem to be 64?

**Comment by jshph** [comment]
Now wondering whether this might be because of discrepancy between scheduler timesteps I compiled with vs. am using in the demo. Still looking.

**Comment by hlky** [comment]
This message suggests your VAE module is compiled for width/height 384px (48 * 8)

**Comment by jshph** [comment]
(assume you meant UNet and not VAE) -- didn't realize that UNet is compiled for static sizes only but now I see that. 👍 

Demo works now!!

I just have a minor suggestion -- the defaults for w/h are (64,2048). I realize that your original PR gave instructions to run compile with the width and height params explicitly set, but it's not obvious. Have you considered whether 512 might be a safer default for the time being?

Thanks again!
