### ISSUE TITLE
run 05_stable_diffusion scripts/compile.py failed

### ISSUE THREAD

**Issue by Lzhang-hub** [facebookincubator/AITemplate#731]
run step:
```
# build docker image
./docker/build.sh cuda
# run docker
docker run -it --gpus=all ait:latest bash
# run scripts
cd /AITemplate/examples/05_stable_diffusion
python3 scripts/compile.py
```

error log:
```
INFO:aitemplate.backend.build_cache_base:Build cache disabled
2023-05-30 07:34:37,955 INFO <aitemplate.testing.detect_target> Set target to CUDA
Traceback (most recent call last):
  File "/data1/nfs15/nfs/bigdata/zhanglei/ml/inference/cv/AITemplate/examples/05_stable_diffusion/scripts/compile.py", line 100, in <module>
    compile_diffusers()
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/data1/nfs15/nfs/bigdata/zhanglei/ml/inference/cv/AITemplate/examples/05_stable_diffusion/scripts/compile.py", line 65, in compile_diffusers
    compile_clip(
  File "/data1/nfs15/nfs/bigdata/zhanglei/ml/inference/cv/AITemplate/examples/05_stable_diffusion/src/compile_lib/compile_clip.py", line 81, in compile_clip
    Y = ait_mod(input_ids=input_ids_ait, position_ids=position_ids_ait)
  File "/usr/local/lib/python3.10/dist-packages/aitemplate/frontend/nn/module.py", line 390, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data1/nfs15/nfs/bigdata/zhanglei/ml/inference/cv/AITemplate/examples/05_stable_diffusion/src/modeling/clip.py", line 640, in forward
    hidden_states = self.embeddings(input_ids=input_ids, position_ids=position_ids)
  File "/usr/local/lib/python3.10/dist-packages/aitemplate/frontend/nn/module.py", line 390, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data1/nfs15/nfs/bigdata/zhanglei/ml/inference/cv/AITemplate/examples/05_stable_diffusion/src/modeling/clip.py", line 563, in forward
    inputs_embeds = ops.batch_gather()(token_embedding, input_ids)
  File "/usr/local/lib/python3.10/dist-packages/aitemplate/compiler/ops/tensor/batch_gather.py", line 96, in __call__
    output_shape = self._infer_shapes(x, indices)
  File "/usr/local/lib/python3.10/dist-packages/aitemplate/compiler/ops/tensor/batch_gather.py", line 73, in _infer_shapes
    y_shape = self._infer_shape(x_shape, indices_shape)
  File "/usr/local/lib/python3.10/dist-packages/aitemplate/compiler/ops/tensor/batch_gather.py", line 59, in _infer_shape
    assert x[r] == indices[r]
AssertionError

```

**Comment by aakhundov** [comment]
Thanks for reporting. @terrychenism could you please take a look? Thanks!

**Comment by terrychenism** [comment]
cannot repro the error from my side.
