### ISSUE TITLE
[fx2ait] "IndexError: list index out of range" when running resnet50

### ISSUE THREAD

**Issue by ymwangg** [facebookincubator/AITemplate#747]
I got the following error:
```
2023-06-06 00:33:29,436 INFO <aitemplate.compiler.ops.conv.conv2d> current: lb_algo: cutlass_h16816fprop_optimized_128x64_32x6_nhwc_align_4_8, LB:1 MID:1024 UB:2048
Traceback (most recent call last):
  File "/home/ubuntu/src/AITemplate/fx2ait/resnet.py", line 17, in <module>
    lowered = lower(model, inputs)
  File "/home/ubuntu/src/AITemplate/fx2ait/fx2ait/lower/lower.py", line 239, in __call__
    lower_result = self.lower_func(split_result, additional_inputs)
  File "/home/ubuntu/src/AITemplate/fx2ait/fx2ait/lower/lower.py", line 218, in lower_func
    lowered_module = self.lower_pass(
  File "/home/ubuntu/src/AITemplate/fx2ait/fx2ait/lower/lower.py", line 122, in lower_pass
    interp_res: AITInterpreterResult = interpreter(module_name, mod, input)
  File "/home/ubuntu/src/AITemplate/fx2ait/fx2ait/lower/lower.py", line 90, in __call__
    interp_result: AITInterpreterResult = interpreter.run()
  File "/home/ubuntu/src/AITemplate/fx2ait/fx2ait/fx2ait.py", line 236, in run
    self.engine = compile_model(**args)
  File "/home/ubuntu/src/AITemplate/python/aitemplate/utils/misc.py", line 93, in inner_function
    return f(*args, **kwargs)
  File "/home/ubuntu/src/AITemplate/python/aitemplate/compiler/compiler.py", line 275, in compile_model
    compiler.transform.profile(
  File "/home/ubuntu/src/AITemplate/python/aitemplate/compiler/transform/profile.py", line 103, in profile
    f.profile(
  File "/home/ubuntu/src/AITemplate/python/aitemplate/compiler/ops/conv/conv2d.py", line 601, in profile
    self._profile_dynamic_dim(workdir)
  File "/home/ubuntu/src/AITemplate/python/aitemplate/compiler/ops/conv/conv2d.py", line 721, in _profile_dynamic_dim
    result_dict = {res.op_config: res for res in result[0][1]}
IndexError: list index out of range
```
while running the following example code with latest master:
```py
import torch
import torchvision
import torch.nn.functional as F
import torch.nn as nn

from fx2ait.lower.lower import AitLowerer
from fx2ait.lower.lower_settings import LowerSettings

model = torchvision.models.resnet18()
model.eval()
model.half().cuda()
inputs = [torch.randn(1, 3, 224, 224).half().cuda()]
ref_output = model(*inputs)
lower = AitLowerer.create(
    LowerSettings(workdir="/tmp", name="test_ait_lower", min_acc_module_size=0)
)
lowered = lower(model, inputs)
lower_output = lowered(*inputs)
torch.testing.assert_close(ref_output, lower_output, check_dtype=False)
```

This may be a duplicate issue of https://github.com/facebookincubator/AITemplate/issues/742 though the models are different.

**Comment by sgrigory** [comment]
@ymwangg I see that the test is using NHWC format of inputs, so could you try `torch.randn(1, 224, 224, 3)` instead of `torch.randn(1, 3, 224, 224)`?
https://github.com/facebookincubator/AITemplate/blob/22a74c7ee3f2b9b2a89cacb675698d7e20106cdf/examples/01_resnet-50/test_correctness.py#L74-L75

Same shape is used by the inference script:
https://github.com/facebookincubator/AITemplate/blob/22a74c7ee3f2b9b2a89cacb675698d7e20106cdf/examples/01_resnet-50/infer_with_torch.py#L54-L55

In any case, we need to improve the error message here. I suspect that the profiler receives a wrong shape, returns empty `result`, and so `result[0][1]` throws an indexing error

**Comment by ymwangg** [comment]
I'm getting
```
INFO:aitemplate.backend.build_cache_base:Build cache disabled
Traceback (most recent call last):
  File "/home/ubuntu/src/AITemplate/fx2ait/resnet.py", line 13, in <module>
    ref_output = model(*inputs)
  File "/home/ubuntu/src/pytorch/torch/nn/modules/module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/src/pytorch/torch/nn/modules/module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/src/pytorch/vision/torchvision/models/resnet.py", line 285, in forward
    return self._forward_impl(x)
  File "/home/ubuntu/src/pytorch/vision/torchvision/models/resnet.py", line 268, in _forward_impl
    x = self.conv1(x)
  File "/home/ubuntu/src/pytorch/torch/nn/modules/module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/src/pytorch/torch/nn/modules/module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/src/pytorch/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/ubuntu/src/pytorch/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [64, 3, 7, 7], expected input[1, 224, 224, 3] to have 3 channels, but got 224 channels instead
```
after changing `torch.randn(1, 3, 224, 224)` to `torch.randn(1, 224, 224, 3)`. I remember fx2ait no longer requires layout conversion on the user side through this [function](https://github.com/facebookincubator/AITemplate/blob/8f622a1245c2ccc137e121b1ad2df9bf3a0d38f1/fx2ait/fx2ait/converters/ait_converters.py#L778).

**Comment by ymwangg** [comment]
It looks like this issue has been fixed and I'm able to run the above script now. Closing.
