### ISSUE TITLE
Stable Diffusion 2.1 768x786 demo.py failed

### ISSUE THREAD

**Issue by apivovarov** [facebookincubator/AITemplate#751]
I tried to compile [stabilityai/stable-diffusion-2-1](https://huggingface.co/stabilityai/stable-diffusion-2-1) using its native resolution 768x768.

I updated model name in `script/download_pipeline.py`.

Then I run  `script/compile.py --width 768 --height 768`.

Compilation works fine

But `script/demo.py --width 768 --height 768` failed with the following error:

Error
```
  0%|                                                                                                                                                                                                | 0/50 [00:00<?, ?it/s][05:05:44] 
model_interface.cu:200: Error: [SetValue] Dimension got value out of bounds; expected value to be in [32, 64], but got 96.
  0%|                                                                                                                                                                                                | 0/50 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/root/workspace/AITemplate/examples/05_stable_diffusion/scripts/demo.py", line 73, in <module>
    run()
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/root/workspace/AITemplate/examples/05_stable_diffusion/scripts/demo.py", line 59, in run
    image = pipe(prompt, height, width).images[0]
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/workspace/AITemplate/examples/05_stable_diffusion/src/pipeline_stable_diffusion_ait.py", line 376, in __call__
    noise_pred = self.unet_inference(
  File "/root/workspace/AITemplate/examples/05_stable_diffusion/src/pipeline_stable_diffusion_ait.py", line 138, in unet_inference
    exe_module.run_with_tensors(inputs, ys, graph_mode=False)
  File "/opt/conda/lib/python3.10/site-packages/aitemplate/compiler/model.py", line 549, in run_with_tensors
    outputs_ait = self.run(
  File "/opt/conda/lib/python3.10/site-packages/aitemplate/compiler/model.py", line 452, in run
    return self._run_impl(
  File "/opt/conda/lib/python3.10/site-packages/aitemplate/compiler/model.py", line 391, in _run_impl
    self.DLL.AITemplateModelContainerRun(
  File "/opt/conda/lib/python3.10/site-packages/aitemplate/compiler/model.py", line 195, in _wrapped_func
    raise RuntimeError(f"Error in function: {method.__name__}")
RuntimeError: Error in function: AITemplateModelContainerRun
```

@terrychenism  @hlky

**Comment by hl475** [comment]
Thanks @hlky !

@apivovarov could you try again with https://github.com/facebookincubator/AITemplate/pull/754 ?

**Comment by hl475** [comment]
I am not sure I am following, but feel free to submit a PR if you already have some solutions in mind!

**Comment by apivovarov** [comment]
SD 2.1 compilation 768x768 worked fine before.
It was broken by [PR611](https://github.com/facebookincubator/AITemplate/pull/611)
The PR does not provide any description and was silently committed without and reviews. @terrychenism

The PR did many strange things including model name downgrade from "stabilityai/stable-diffusion-2-1-base" to "runwayml/stable-diffusion-v1-5".

**Comment by apivovarov** [comment]
The fix - https://github.com/facebookincubator/AITemplate/pull/755
Tested for both SD models editions
- base model edition - 512x512 - `stabilityai/stable-diffusion-2-1-base`
- regular model edition - 768x768  - `stabilityai/stable-diffusion-2-1`

**Comment by apivovarov** [comment]
I opened follow-up PR 757 to Add `--model-name` param to SD `download_pipeline script`
