### ISSUE TITLE
Unsupported platform while using A10g instance on AWS

### ISSUE THREAD

**Issue by tomerkeren42** [facebookincubator/AITemplate#779]
Hi, I'm trying to launch the stable diffusion example.

I launched AWS instance `g5.xlarge` (A10g), and installed CUDA 11.6 and NVCC as follows:
```+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A10G         On   | 00000000:00:1E.0 Off |                    0 |
|  0%   25C    P8    19W / 300W |      0MiB / 23028MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

``` (base) ubuntu@ip-10-1-8-231:~$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```

I then cloned the repo, built the image and installed relevant packages within the container.
Downloaded model (version 2.1) from huggingface and tried to compile, while I encounter this error no matter what I try:

```
root@df8bc07bf471:/home/ubuntu/AITemplate/examples/05_stable_diffusion# python3 scripts/compile.py
INFO:aitemplate.backend.build_cache_base:Build cache disabled
Traceback (most recent call last):
  File "scripts/compile.py", line 26, in <module>
    from src.compile_lib.compile_clip import compile_clip
  File "/home/ubuntu/AITemplate/examples/05_stable_diffusion/src/compile_lib/compile_clip.py", line 20, in <module>
    from ..modeling.clip import CLIPTextTransformer as ait_CLIPTextTransformer
  File "/home/ubuntu/AITemplate/examples/05_stable_diffusion/src/modeling/clip.py", line 24, in <module>
    USE_CUDA = detect_target().name() == "cuda"
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/testing/detect_target.py", line 132, in detect_target
    raise RuntimeError("Unsupported platform")
RuntimeError: Unsupported platform
```

Waiting for support, thanks in advanced!

**Comment by ipiszy** [comment]
A10G should be supported here:https://github.com/facebookincubator/AITemplate/blob/main/python/aitemplate/testing/detect_target.py#L45

Could you try "nvidia-smi --query-gpu=gpu_name --format=csv" locally? What's the output?

**Comment by tomerkeren42** [comment]
Thanks, it was my bad - different installations of CUDA drivers in the host machine wouldn't be recognized by docker correctly.
