### ISSUE TITLE
Error compiling stable diffusion examples

### ISSUE THREAD

**Issue by xiankgx** [facebookincubator/AITemplate#780]
Hi, I'm having trouble compiling Stable Diffusion 1.5 using `python3/scripts/compile.py` within the `examples/05_stable_diffusion` directory. I'm doing this on a g5.2xlarge instance on AWS. What could be wrong?

```
2023-06-19 07:51:31,354 INFO <aitemplate.backend.builder> make stderr:

gcc: internal compiler error: Segmentation fault signal terminated program cc1plus
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-9/README.Bugs> for instructions.
make: *** [Makefile:9: model_container.obj] Error 255
make: *** Waiting for unfinished jobs....

Traceback (most recent call last):
  File "scripts/compile.py", line 100, in <module>
    compile_diffusers()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "scripts/compile.py", line 77, in compile_diffusers
    compile_unet(
  File "/workspace/AITemplate/examples/05_stable_diffusion/src/compile_lib/compile_unet.py", line 99, in compile_unet
    compile_model(Y, target, "./tmp", model_name, constants=params_ait)
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/utils/misc.py", line 93, in inner_function
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/compiler.py", line 343, in compile_model
    compile_engine.make(
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/backend/builder.py", line 898, in make
    _run_make_cmds(cmds, self._timeout, build_dir, allow_cache=allow_cache)
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/backend/builder.py", line 183, in _run_make_cmds
    raise RuntimeError("Build has failed.")
RuntimeError: Build has failed.
```

**Comment by xiankgx** [comment]
I'm also compiling within the Docker container that was built running `./docker/build.sh cuda`.

**Comment by apivovarov** [comment]
Hi GX, I tried to compile for aws instances (g4dn, g5 and p4d) - it works fine.
Step by step doc is [Compile Stable Diffusion Model with AITemplate and Deploy it as AWS Sagemaker Endpoint](https://github.com/apivovarov/kb/blob/main/Sagemaker/AITemplate/compile-and-deploy.md)

**Comment by xiankgx** [comment]
I tried with a different and possibly newer EC2 instance and could compile without issues.
