### ISSUE TITLE
The size of tensor a (64) must match the size of tensor b (128) at non-singleton dimension 3

### ISSUE THREAD

**Issue by o5faruk** [facebookincubator/AITemplate#789]
Ok, so I have a .ckpt file that I converted to diffusers and have it in the folder on A10

I ran compile_alt with width and height 512 1024 batch size 1 4, clip-chunks 6 and include constants

I then run demo.py and get this error back, any help is appreciated!

Traceback (most recent call last):
  File "scripts/demo.py", line 66, in <module>
    run()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "scripts/demo.py", line 55, in run
    images = pipe(prompt, height, width).images
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workdir/app/aitemplate/src/pipeline_stable_diffusion_ait.py", line 393, in __call__
    latents = self.scheduler.step(
  File "/usr/local/lib/python3.8/dist-packages/diffusers/schedulers/scheduling_euler_discrete.py", line 335, in step
    pred_original_sample = sample - sigma_hat * model_output
RuntimeError: The size of tensor a (64) must match the size of tensor b (128) at non-singleton dimension 3

**Comment by hlky** [comment]
Use `demo_alt.py` instead. 

The regular pipeline does not [adjust height/width](https://github.com/facebookincubator/AITemplate/blob/0cf1c2ea56df8d75aac0cc7051faad83d737753b/examples/05_stable_diffusion/src/pipeline_stable_diffusion_ait.py#L134-L137) from the module's maximum values. Alt pipeline sets [height/width](https://github.com/facebookincubator/AITemplate/blob/0cf1c2ea56df8d75aac0cc7051faad83d737753b/examples/05_stable_diffusion/src/pipeline_stable_diffusion_ait_alt.py#L796-L801) according to the current generation's shape.

**Comment by o5faruk** [comment]
@hlky That was it! Thanks

**Comment by arthur-71** [comment]
I am having the exact same issue, but the answer seems to have been removed or deleted.

@o5faruk could you please tell me what was the solution ?

**Comment by o5faruk** [comment]
@arthur-71 If I remember correctly, I had to run it usin demo_alt.py instead of demo.py, but Im not really sure. I ended up not using AIT at all so I dont even have the old code anymore.

**Comment by arthur-71** [comment]
You are correct, it worked using demo_alt.py !
Thank you very much !
