### ISSUE TITLE
Error when run stable diffusion with controlnet. 

### ISSUE THREAD

**Issue by cr7Por** [facebookincubator/AITemplate#797]
step1: python3 scripts/compile_alt.py --width 64 1536 --height 64 1536 --batch-size 1 4 --clip-chunks 6 --controlnet True
The result of step1 is still UNet2DConditionModel/ not ControlNetUNet2DConditionModel/
step2: python3 scripts/compile_controlnet.py --width 1024 --height 1024 --clip-chunks 6
step3: python3 scripts/demo_controlnet.py --width 1024 --height 1024
then when call unet_inference, get "ValueError: Did not get correct number of inputs expected 3, got 16."
I think the reason is ait unet model don't expect those 'down_block_residual' layers.  
How can I fix this?

**Comment by hlky** [comment]
>ValueError: Did not get correct number of inputs expected 3, got 16.
The error comes from using regular UNet with ControlNet, it is required to use a Control UNet with ControlNet modules.

After compiling UNet with `--controlnet True` you can simply rename `UNet2DConditionModel` to `ControlNetUNet2DConditionModel`, or [adjust the name here](https://github.com/facebookincubator/AITemplate/blob/0cf1c2ea56df8d75aac0cc7051faad83d737753b/examples/05_stable_diffusion/src/pipeline_stable_diffusion_controlnet_ait.py#L686).

**Comment by JJHu1993** [comment]
@cr7Por  similar problem with controlnet

**Comment by JJHu1993** [comment]
@hlky I change the folder name and still got error:
`model_interface.cu:200: Error: [SetValue] Dimension got value out of bounds; expected value to be in [8, 8], but got 64.
  0%|                                                                                                                                                                               | 0/50 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "./scripts/demo_controlnet.py", line 140, in <module>
    run()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "./scripts/demo_controlnet.py", line 127, in run
    image = pipe(
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/AITemplate/examples/05_stable_diffusion/src/pipeline_stable_diffusion_controlnet_ait.py", line 1037, in __call__
    noise_pred = self.unet_inference(
  File "/AITemplate/examples/05_stable_diffusion/src/pipeline_stable_diffusion_controlnet_ait.py", line 806, in unet_inference
    exe_module.run_with_tensors(inputs, ys, graph_mode=False)
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/model.py", line 549, in run_with_tensors
    outputs_ait = self.run(
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/model.py", line 452, in run
    return self._run_impl(
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/model.py", line 391, in _run_impl
    self.DLL.AITemplateModelContainerRun(
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/model.py", line 195, in _wrapped_func
    raise RuntimeError(f"Error in function: {method.__name__}")
RuntimeError: Error in function: AITemplateModelContainerRun
`

**Comment by hlky** [comment]
`compile_alt.py` with `--controlnet True` uses the [first values](https://github.com/facebookincubator/AITemplate/blob/0cf1c2ea56df8d75aac0cc7051faad83d737753b/examples/05_stable_diffusion/src/compile_lib/compile_unet_alt.py#L88-L94) of your height/width pairs because it supports only static shape.
Try like this `--width 512 512 --height 512 512`.
I actually have dynamic shape for ControlNet working, I just haven't made a pull request for those changes yet.

**Comment by JJHu1993** [comment]
@hlky Thanks very much. It works. However, the result is worse than that of the standard pt model. Since my gpu is rtx  quadro 5000 (sm75), I change the `Conv2dBiasFewChannels` to `Conv2dBias` in `ControlNetConditioningEmbedding` class, and comment the `conditioning = pad(conditioning)` in this class, and comment  `    params_ait["controlnet_cond_embedding_conv_in_weight"] = torch.nn.functional.pad(
        params_ait["controlnet_cond_embedding_conv_in_weight"], (0, 1, 0, 0, 0, 0, 0, 0)
    )` in `pipeline_stable_diffusion_controlnet_ait.py` file.

Is this way right? and any other process will lead to the different result?

**Comment by hlky** [comment]
Module will not compile without padding. AIT Conv2dBias does not support 3 in channels.

I haven't heard of anyone else having issues with ControlNet on SM75, as far as I know people have successfully generated good images with the pre-compiled modules I provide for the ComfyUI custom node. Without seeing what you are seeing it is impossible for me to tell why your image is "worse".

**Comment by JJHu1993** [comment]
@hlky similar issue with https://github.com/facebookincubator/AITemplate/issues/583#issue-1669518655

controlnet also uses conv2dbiasfewchannels as conv_in

**Comment by hlky** [comment]
@JJHu1993 without padding the module will not compile.

```
2023-06-27 22:01:59,517 INFO <aitemplate.compiler.ops.conv.conv2d> Profile: conv2d_bias_61: NI == 1 && HI == 1024 && WI == 1024 && CI == 3
Traceback (most recent call last):
  File "H:\venv\aitemplate\Lib\site-packages\aitemplate\compiler\ops\conv\conv2d.py", line 632, in _profile_static
    best_algo, workspace = self._profile_single_workload(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\venv\aitemplate\Lib\site-packages\aitemplate\compiler\ops\conv\conv2d.py", line 495, in _profile_single_workload
    tmp_key = next(iter(self._attrs["op_instance"].keys()))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration
```

**Comment by JJHu1993** [comment]
@hlky `Conv2dBias` with padding in my environment, this error occurs:
`Traceback (most recent call last):
  File "scripts/compile_controlnet.py", line 86, in <module>
    compile_diffusers()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "scripts/compile_controlnet.py", line 73, in compile_diffusers
    compile_controlnet(
  File "/AITemplate/examples/05_stable_diffusion/src/compile_lib/compile_controlnet.py", line 106, in compile_controlnet
    Y = ait_mod(
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/frontend/nn/module.py", line 390, in _call_impl
    return forward_call(*input, **kwargs)
  File "/AITemplate/examples/05_stable_diffusion/src/modeling/controlnet_unet_2d_condition.py", line 210, in forward
    controlnet_cond = self.controlnet_cond_embedding(controlnet_cond)
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/frontend/nn/module.py", line 390, in _call_impl
    return forward_call(*input, **kwargs)
  File "/AITemplate/examples/05_stable_diffusion/src/modeling/controlnet_unet_2d_condition.py", line 66, in forward
    embedding = self.conv_in(conditioning)
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/frontend/nn/module.py", line 390, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/frontend/nn/conv2d/common_conv2d_bias_act.py", line 76, in forward
    return self.op(x, self.weight.tensor(), self.bias.tensor())
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/ops/conv/common_conv2d_bias_activation.py", line 68, in __call__
    output_shape = self._infer_shapes(x, w)
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/ops/conv/conv2d.py", line 255, in _infer_shapes
    y_shape = self._infer_shape(x_shape, w_shape)
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/ops/conv/conv2d.py", line 221, in _infer_shape
    raise RuntimeError("X/W Shape mismatch for conv2d")
RuntimeError: X/W Shape mismatch for conv2d
`

**Comment by hlky** [comment]
@JJHu1993 without padding the module will not compile. `Conv2dBiasFewChannels` auto pads. `Conv2dBias` does not, so you need to set the channels to 4.

**Comment by cr7Por** [comment]
Thanks, I have make it work. One more thing, use torch 1.13+cuda117, torch2.0 will still get the ValueError.
> > ValueError: Did not get correct number of inputs expected 3, got 16.
> 
> The error comes from using regular UNet with ControlNet, it is required to use a Control UNet with ControlNet modules.
> 
> After compiling UNet with `--controlnet True` you can simply rename `UNet2DConditionModel` to `ControlNetUNet2DConditionModel`,

**Comment by hlky** [comment]
Torch version is unrelated to using incorrect modules.

**Comment by DhruvThu** [comment]
> `compile_alt.py` with `--controlnet True` uses the [first values](https://github.com/facebookincubator/AITemplate/blob/0cf1c2ea56df8d75aac0cc7051faad83d737753b/examples/05_stable_diffusion/src/compile_lib/compile_unet_alt.py#L88-L94) of your height/width pairs because it supports only static shape. Try like this `--width 512 512 --height 512 512`. I actually have dynamic shape for ControlNet working, I just haven't made a pull request for those changes yet.

Is it possible to have update for dynamic shape?
