### ISSUE TITLE
Error for compiling controlnet 

### ISSUE THREAD

**Issue by mzeynali** [facebookincubator/AITemplate#808]
Hi guys,
I converted the controlnet with [compile_controlnet.py](https://github.com/facebookincubator/AITemplate/blob/main/examples/05_stable_diffusion/scripts/compile_controlnet.py) file with command `python3 compile_controlnet.py`.

After that I renamed  `UNet2DConditionModel` to `ControlNetUNet2DConditionModel`, then I run `python3 scripts/demo_controlnet.py`, throw the below error:

`[06:37:57] model_container.cu:87: Init AITemplate Runtime with 1 concurrency
Loading PyTorch VAE
Mapping parameters...
Setting constants
Folding constants
  0%|                                                                                                                                                                                       | 0/50 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "scripts/demo_controlnet.py", line 140, in <module>
    run()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "scripts/demo_controlnet.py", line 127, in run
    image = pipe(
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/AITemplate/examples/05_stable_diffusion/src/pipeline_stable_diffusion_controlnet_ait.py", line 1029, in __call__
    noise_pred = self.unet_inference(
  File "/AITemplate/examples/05_stable_diffusion/src/pipeline_stable_diffusion_controlnet_ait.py", line 802, in unet_inference
    exe_module.run_with_tensors(inputs, ys, graph_mode=False)
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/model.py", line 587, in run_with_tensors
    outputs_ait = self.run(
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/model.py", line 490, in run
    return self._run_impl(
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/model.py", line 419, in _run_impl
    inputs = self._dict_to_ordered_list(inputs, is_inputs=True)
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/model.py", line 342, in _dict_to_ordered_list
    raise ValueError(
ValueError: Did not get correct number of inputs expected 3, got 16
`

**Comment by sgrigory** [comment]
HI @mzeynali, I think what happened is that you used `UNet2DConditionModel` in place of `ControlNetUNet2DConditionModel` - they take different number of parameters ([here](https://github.com/facebookincubator/AITemplate/blob/039bb9ff46656e5422bf6d389ea97174bc9612c7/examples/05_stable_diffusion/src/modeling/unet_2d_condition.py#L183-L191) and [here](https://github.com/facebookincubator/AITemplate/blob/039bb9ff46656e5422bf6d389ea97174bc9612c7/examples/05_stable_diffusion/src/modeling/controlnet_unet_2d_condition.py#L430-L449)) and so aren't drop-in replacements for each other. As described in https://github.com/facebookincubator/AITemplate/pull/713, you can compile `ControlNetUNet2DConditionModel` with `python scripts/compile_alt.py --width 512 --height 512 --controlnet True`. Following the steps outlined in that PR description should work, let me know if it doesn't

**Comment by mzeynali** [comment]
@sgrigory That's ok and works.
