### ISSUE TITLE
Error in compiling dynamic resolution on SD 1.5

### ISSUE THREAD

**Issue by MahdiMohseni0033** [facebookincubator/AITemplate#864]
Hi
thanks for your great work . 
I've used your docker to compiling dynamic resolution on SD 1.5 , but  I've face with following Error :
```
Traceback (most recent call last):
  File "scripts/compile_alt.py", line 138, in <module>
    compile_diffusers()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "scripts/compile_alt.py", line 126, in compile_diffusers
    compile_vae(
  File "/AITemplate/examples/05_stable_diffusion/src/compile_lib/compile_vae_alt.py", line 185, in compile_vae
    compile_model(
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/utils/misc.py", line 93, in inner_function
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/compiler.py", line 276, in compile_model
    compiler.transform.profile(
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/transform/profile.py", line 104, in profile
    f.profile(
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/ops/conv/conv2d.py", line 601, in profile
    self._profile_dynamic_dim(workdir)
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/ops/conv/conv2d.py", line 721, in _profile_dynamic_dim
    result_dict = {res.op_config: res for res in result[0][1]}
IndexError: list index out of range

```

**Comment by hlky** [comment]
You may be OOM while profiling VAE. The default height, width range is 64, 2048 and batch size 1, 4, for VAE this is ~21GB.

Try lower batch size e.g. `--batch-size 1 1` or lowering resolution.
