### ISSUE TITLE
Error to run examples on ROCm 

### ISSUE THREAD

**Issue by duli2012** [facebookincubator/AITemplate#91]
Hello, 

When I run the examples in the ROCm docker, I always get the following error:
Traceback (most recent call last):
  File "examples/07_how_to_run_pt_model/how_to_run_pt_model.py", line 131, in <module>
    verify_simple_model()
  File "examples/07_how_to_run_pt_model/how_to_run_pt_model.py", line 97, in verify_simple_model
    with compile_model(
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/compiler.py", line 200, in compile_model
    compiler.transform.profile(
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/transform/profile.py", line 79, in profile
    codegen.gen_profiler(sorted_graph, profiler_dir, dynamic_profiling_strategy)
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/backend/codegen.py", line 71, in gen_profiler
    results.append(func.gen_profiler(workdir, dynamic_profiling_strategy))
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/ops/gemm_universal/gemm_common.py", line 509, in gen_profiler
    return func(
TypeError: gemm_gen_profiler() takes 3 positional arguments but 4 were given

Could you please help to fix it?

Thanks.

Du

**Comment by duli2012** [comment]
Thanks @antinucleon for the prompt response！

Du

**Comment by EzioZz** [comment]
I have found same problem while running example 03_bert.
is this problem solved?

**Comment by fsx950223** [comment]
Maybe there should be a link direct to rocm fork in AITemplate README.
