### ISSUE TITLE
op b2b_bmm report an error "no module named cutlass_lib'

### ISSUE THREAD

**Issue by yumesann** [facebookincubator/AITemplate#923]
There is 'import cutlass_lib" in b2b_bmm_base.py  __init__ and this leads to an error.
Is it a bug or anything I do wrong?
see also #511

**Comment by ipiszy** [comment]
Did you call `target = detect_target()` before initializing `b2b_bmm`? As https://github.com/facebookincubator/AITemplate/issues/511 mentioned, there is a bug that b2b_bmm must be called after Target is defined.

**Comment by yumesann** [comment]
@ipiszy Thank you for replying. I already do so, and still doesn't work. See this
`
INFO:aitemplate.backend.build_cache_base:Build cache disabled
2023-09-07 01:56:28,240 INFO <aitemplate.testing.detect_target> Set target to CUDA
Traceback (most recent call last):
  File "test_code/test_classic_bmm_relu.py", line 103, in <module>
    _test_classic_b2b_bmm()
  File "test_code/test_classic_bmm_relu.py", line 65, in _test_classic_b2b_bmm
    classic_b2b_bmm_op = ops.classic_b2b_bmm(
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/ops/b2b_bmm/classic_b2b_bmm.py", line 78, in __init__
    super().__init__(
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/ops/b2b_bmm/b2b_bmm_base.py", line 87, in __init__
    import cutlass_lib
ModuleNotFoundError: No module named 'cutlass_lib'`

**Comment by ipiszy** [comment]
Could you try it using "with" clause?
```
with detect_target() as target:
    xxxx
```
It's called here: https://github.com/facebookincubator/AITemplate/blob/6bbe03c7128104c8ceb0e88dea09b39429e8cb9e/python/aitemplate/backend/cuda/target_def.py#L224. You could also add some breakpoint() to debug.
