### ISSUE TITLE
fx2ait install error -- c10::StorageImpl has no member named mutable_data

### ISSUE THREAD

**Issue by CanyonWind** [facebookincubator/AITemplate#940]
Attaching the error log below, would really appreciate some suggestions

```
Emitting ninja build file /home/username/AITemplate/fx2ait/build/temp.linux-x86_64-cpython-310/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] c++ -MMD -MF /home/username/AITemplate/fx2ait/build/temp.linux-x86_64-cpython-310/home/username/AITemplate/fx2ait/fx2ait/csrc/AITModelImpl.o.d -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/home/username/AITemplate/fx2ait/fx2ait/csrc -I/home/username/AITemplate/static/include -I/home/username/AITemplate/3rdparty/picojson -I/opt/venv/lib/python3.10/site-packages/torch/include -I/opt/venv/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/opt/venv/lib/python3.10/site-packages/torch/include/TH -I/opt/venv/lib/python3.10/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/venv/include -I/usr/include/python3.10 -c -c /home/username/AITemplate/fx2ait/fx2ait/csrc/AITModelImpl.cpp -o /home/username/AITemplate/fx2ait/build/temp.linux-x86_64-cpython-310/home/username/AITemplate/fx2ait/fx2ait/csrc/AITModelImpl.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1013"' -DTORCH_EXTENSION_NAME=libait_model -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++17
FAILED: /home/username/AITemplate/fx2ait/build/temp.linux-x86_64-cpython-310/home/username/AITemplate/fx2ait/fx2ait/csrc/AITModelImpl.o 
c++ -MMD -MF /home/username/AITemplate/fx2ait/build/temp.linux-x86_64-cpython-310/home/username/AITemplate/fx2ait/fx2ait/csrc/AITModelImpl.o.d -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/home/username/AITemplate/fx2ait/fx2ait/csrc -I/home/username/AITemplate/static/include -I/home/username/AITemplate/3rdparty/picojson -I/opt/venv/lib/python3.10/site-packages/torch/include -I/opt/venv/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/opt/venv/lib/python3.10/site-packages/torch/include/TH -I/opt/venv/lib/python3.10/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/venv/include -I/usr/include/python3.10 -c -c /home/username/AITemplate/fx2ait/fx2ait/csrc/AITModelImpl.cpp -o /home/username/AITemplate/fx2ait/build/temp.linux-x86_64-cpython-310/home/username/AITemplate/fx2ait/fx2ait/csrc/AITModelImpl.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1013"' -DTORCH_EXTENSION_NAME=libait_model -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++17
/home/username/AITemplate/fx2ait/fx2ait/csrc/AITModelImpl.cpp: In member function ‘void torch::aitemplate::AITModelImpl::allocateOutputs(std::vector<c10::intrusive_ptr<c10::StorageImpl> >&, std::vector<AITData>&, std::vector<std::vector<long int> >&, std::vector<long int*>&, const c10::Device&)’:
/home/username/AITemplate/fx2ait/fx2ait/csrc/AITModelImpl.cpp:328:44: error: ‘struct c10::StorageImpl’ has no member named ‘mutable_data’
  328 |     ait_outputs.emplace_back(storage_impl->mutable_data(), shape, ait_dtype);
      |                                            ^~~~~~~~~~~~
/home/username/AITemplate/fx2ait/fx2ait/csrc/AITModelImpl.cpp: In member function ‘std::vector<AITData> torch::aitemplate::AITModelImpl::processInputs(std::vector<at::Tensor>&, std::vector<at::Tensor>&)’:
/home/username/AITemplate/fx2ait/fx2ait/csrc/AITModelImpl.cpp:385:51: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<std::__cxx11::basic_string<char> >::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
  385 |   for (int python_input_idx = 0; python_input_idx < input_names_.size();
      |                                  ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
/home/username/AITemplate/fx2ait/fx2ait/csrc/AITModelImpl.cpp: In function ‘c10::ScalarType torch::aitemplate::{anonymous}::AITemplateDtypeToTorchDtype(AITemplateDtype)’:
/home/username/AITemplate/fx2ait/fx2ait/csrc/AITModelImpl.cpp:261:1: warning: control reaches end of non-void function [-Wreturn-type]
  261 | }
      | ^
[2/2] c++ -MMD -MF /home/username/AITemplate/fx2ait/build/temp.linux-x86_64-cpython-310/home/username/AITemplate/fx2ait/fx2ait/csrc/AITModel.o.d -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/home/username/AITemplate/fx2ait/fx2ait/csrc -I/home/username/AITemplate/static/include -I/home/username/AITemplate/3rdparty/picojson -I/opt/venv/lib/python3.10/site-packages/torch/include -I/opt/venv/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/opt/venv/lib/python3.10/site-packages/torch/include/TH -I/opt/venv/lib/python3.10/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/venv/include -I/usr/include/python3.10 -c -c /home/username/AITemplate/fx2ait/fx2ait/csrc/AITModel.cpp -o /home/username/AITemplate/fx2ait/build/temp.linux-x86_64-cpython-310/home/username/AITemplate/fx2ait/fx2ait/csrc/AITModel.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1013"' -DTORCH_EXTENSION_NAME=libait_model -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++17
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
    subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/username/AITemplate/fx2ait/setup.py", line 70, in <module>
    setup(
  File "/opt/venv/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "/opt/venv/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/opt/venv/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/opt/venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/opt/venv/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/opt/venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/opt/venv/lib/python3.10/site-packages/setuptools/command/install.py", line 80, in run
    self.do_egg_install()
  File "/opt/venv/lib/python3.10/site-packages/setuptools/command/install.py", line 129, in do_egg_install
    self.run_command('bdist_egg')
  File "/opt/venv/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/opt/venv/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/opt/venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/opt/venv/lib/python3.10/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/opt/venv/lib/python3.10/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/opt/venv/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/opt/venv/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/opt/venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/opt/venv/lib/python3.10/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/opt/venv/lib/python3.10/site-packages/setuptools/_distutils/command/install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "/opt/venv/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/opt/venv/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/opt/venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/opt/venv/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/opt/venv/lib/python3.10/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/opt/venv/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
    self.build_extensions()
  File "/opt/venv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
    build_ext.build_extensions(self)
  File "/opt/venv/lib/python3.10/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/opt/venv/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "/opt/venv/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "/opt/venv/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "/opt/venv/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
    objects = self.compiler.compile(
  File "/opt/venv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 658, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/opt/venv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1574, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/opt/venv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```

**Comment by CanyonWind** [comment]
dup of https://github.com/facebookincubator/AITemplate/issues/778, upgrading pytorch to 2.2.0 resolved the issue.
