### ISSUE TITLE
gemm_gen_profiler() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by jiagaoxiang** [facebookincubator/AITemplate#974]
root@183c2edf89ec:/home/aac/AITemplate/examples/05_stable_diffusion# python3 scripts/compile_alt.py --width 64 1536 --height 64 1536 --batch-size 1 4 --clip-chunks 6 --local-dir tmp/diffusers-pipeline/stabilityai/stable-diffusion-v2/
INFO:aitemplate.backend.build_cache_base:Build cache disabled
2023-12-07 23:06:16,574 INFO <aitemplate.testing.detect_target> Set target to ROCM
Loading pipeline components...:  40%|█████████████████▌                          | 2/5 [00:00<00:00,  5.29it/s]/opt/conda/envs/py_3.10/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Loading pipeline components...: 100%|████████████████████████████████████████████| 5/5 [00:00<00:00,  8.12it/s]
AIT output_0 shape: [[1, 4], [77], [1024]]
2023-12-07 23:06:18,183 INFO <aitemplate.compiler.compiler> Start to compile AIT model. test_dir='./tmp/CLIPTextModel'
2023-12-07 23:06:18,184 INFO <aitemplate.backend.target> Loading profile cache from: /root/.aitemplate/rocm.db
2023-12-07 23:06:18,184 INFO <aitemplate.backend.profiler_cache> table_name='rocm_gemm_3' exists in the db
2023-12-07 23:06:18,184 INFO <aitemplate.backend.profiler_cache> table_name='rocm_conv_3' exists in the db
2023-12-07 23:06:18,184 INFO <aitemplate.backend.profiler_cache> table_name='rocm_conv3d_3' exists in the db
2023-12-07 23:06:18,762 INFO <aitemplate.compiler.compiler> optimized graph elapsed time: 0:00:00.457665
2023-12-07 23:06:18,768 INFO <aitemplate.compiler.transform.refine_graph> reduced unique ops from 516 to 20
2023-12-07 23:06:18,768 INFO <aitemplate.compiler.transform.profile> Force profiler cache = False
2023-12-07 23:06:19,673 INFO <aitemplate.compiler.ops.gemm_universal.gemm_common> generating profiler_filename='gemm_rcr_bias_dfae740faacc263dd40966c310fe9b2cd0b1cd6a_3'
Traceback (most recent call last):
  File "/home/aac/AITemplate/examples/05_stable_diffusion/scripts/compile_alt.py", line 138, in <module>
    compile_diffusers()
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/aac/AITemplate/examples/05_stable_diffusion/scripts/compile_alt.py", line 98, in compile_diffusers
    compile_clip(
  File "/home/aac/AITemplate/examples/05_stable_diffusion/src/compile_lib/compile_clip_alt.py", line 88, in compile_clip
    compile_model(
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/aitemplate/utils/misc.py", line 93, in inner_function
    return f(*args, **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/aitemplate/compiler/compiler.py", line 276, in compile_model
    compiler.transform.profile(
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/aitemplate/compiler/transform/profile.py", line 84, in profile
    codegen.gen_profiler(sorted_graph, profiler_dir, dynamic_profiling_strategy)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/aitemplate/backend/codegen.py", line 91, in gen_profiler
    results.append(func.gen_profiler(workdir, dynamic_profiling_strategy))
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/aitemplate/compiler/ops/gemm_universal/gemm_common.py", line 550, in gen_profiler
    return func(
TypeError: gemm_gen_profiler() takes 3 positional arguments but 4 were given

**Comment by chenyang78** [comment]
Thanks, @fsx950223 ! Closing the issue as we moved it to the ROCM branch.
