### ISSUE TITLE
gcc: internal compiler error

### ISSUE THREAD

**Issue by jiangwei221** [facebookincubator/AITemplate#980]
Hi AITemplate team:
I'm compiling a stable-diffusion-like model with dynamic shapes. The program failed to compile and returned the following error:

```
2023-12-22 06:39:02,736 INFO <aitemplate.backend.builder> make stderr:

gcc: internal compiler error: Segmentation fault signal terminated program cc1plus
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-9/README.Bugs> for instructions.
make: *** [Makefile:9: model_container.obj] Error 255

Traceback (most recent call last):
  balabala_stack
  File "balabala.py", line 322, in balabala_func
    compile_model(y_ait, target, "./tmp", "balabala_model", constants=weights)
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/utils/misc.py", line 93, in inner_function
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/compiler.py", line 343, in compile_model
    compile_engine.make(
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/backend/builder.py", line 914, in make
    _run_make_cmds(cmds, self._timeout, build_dir, allow_cache=allow_cache)
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/backend/builder.py", line 183, in _run_make_cmds
    raise RuntimeError("Build has failed.")
RuntimeError: Build has failed.
```

There is a similar issue #780 , the author of issue 780 solved it by using a newer EC2.
Do you have any thoughts on it?

Update1:
I tried to upgrade gcc(maybe not a good idea...), and the model can pass the compilation.
But when I tried to execute it with tensor, I get following error.
```
In [2]: module.run_with_tensors(inputs, outputs)
[15:39:10] model.h:29: Got error: invalid configuration argument enum: 9 at model-generated.h: 25947
[15:39:10] model_interface.cu:221: Error: Got error: invalid configuration argument enum: 9 at model-generated.h: 25947
```

**Comment by aakhundov** [comment]
@jiangwei221 If this is still relevant, I'll need some repro to investigate the error. Ideally, a minimal repro.

**Comment by jiangwei221** [comment]
I think upgrading gcc to gcc10 works!
The `invalid configuration` error is caused by something else.
